### ISSUE TITLE
Error in bulk apns notifications

### ISSUE THREAD

**Issue by lvelezsantos** [jleclanche/django-push-notifications#122]
when sending notifications in bulk APNs. if a registration id wrong, those still in the list are not sent because the socket is closed. if the first registration id have problems no notification is not sent.

**Comment by Alp-Phone** [comment]
This is a known issue and an immense shortcoming of Apple's APNS API. Hopefully it'll all go away soon: #170

**Comment by somghosh** [comment]
Thanks @jleclanche  I wanted to check if this issue has been rectified yet and if there is a new API that makes things simpler
