### ISSUE TITLE
abstract base class of Device?

### ISSUE THREAD

**Issue by pcompassion** [jleclanche/django-push-notifications#125]
I'd like to add fields to the device models and found GCM / APNS are concrete classes.

I guess this is not specific question  to django-push-notifications.   

How would I go about adding additional fields to devices?

**Comment by jleclanche** [comment]
Yeah this is something django is not really great at. I suspect I could simply provide abstract versions of my models and use those in the library itself, but they'd still get registered so I don't see the point.

**Comment by pcompassion** [comment]
What do you mean by `get registered` ? 

Does it mean creating a table for the model?

**Comment by jleclanche** [comment]
Yes.
