### ISSUE TITLE
New column: `installation_id`

### ISSUE THREAD

**Issue by adamsc64** [jleclanche/django-push-notifications#127]
Using `TelephonyManager.getDeviceId()` to identify GCM installations is considered a major industry antipattern. See http://android-developers.blogspot.com/2011/03/identifying-app-installations.html.

I notice that for `device_id` field for a `GCMDevice` model object, we actually recommend that users store the return value of `TelephonyManager.getDeviceId()`. (see https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/models.py#L49). But there may be problems with recommending that people use this value to identify installations. I believe that most developers just assume this is what this field is for.

So following on this article, I propose that the project would create a new field, `installation_id`. Maybe even we deprecate `device_id`, slate to go away in a few versions or something. Wondering what people think about these ideas. Maybe I'm entirely off-base or overlooking something however.

Happy to help with a PR.

**Comment by jleclanche** [comment]
What's the point? What you're proposing essentially amounts to renaming the field.

**Comment by jleclanche** [comment]
Note that device_id is completely optional.

**Comment by adamsc64** [comment]
Hi @jleclanche, thanks for the reply.

Encouraging developers to store `TelephonyManager.getDeviceId()`, as the project does, may be problematic:
1. This method does not return a value for devices that do not have telephony hardware: wifi-only devices, tablets, music players.
2. Device ids survive factory resets. Saving device ids for an app will not allow a way to anonymize past phone ownership. It potentially links user data across device owners. Phone owners may believe that factory-resetting the phone should be sufficient to anonymize themselves and sell a phone, for example.
3. Accessing this method requires an extra `READ_PHONE_STATE` permission for no good reason.
4. Sometimes `TelephonyManager.getDeviceId()` returns zeros or asterisks (rare).

Source is Tim Bray's article linked above.

I'm not necessarily proposing removing the `device_id` column. However I'm not sure what a good use case is for recommending storing `TelephonyManager.getDeviceId()`.

I do think there's a legitimate use case for storing a uuid to identify installations, but this is different in that its uniqueness is guaranteed by the randomness of the algorithm chosen to generate the uuid, not contingent on telephony hardware implementation of a vendor. What I propose above would differ from simply renaming the column in two ways:
1. Some sort of deprecation policy or migration guideline for developers, with caveats about saving device ids.
2. I propose we create a column `installation_id`, not _necessarily_ remove `device_id`. However, I'd probably recommend the project consider getting rid of it for the reasons stated above.

I suppose there are other possibilities, such as:
- Keep the column name `device_id` for legacy reasons, but don't recommend using `TelephonyManager.getDeviceId()`. Instead we could recommend that developers generating a uuid. We could even provide code for this.

**Comment by jleclanche** [comment]
The column is just *there* if people want to use it though. I could remove it, but the only reason to remove it would be to prevent people from potentially shooting themselves in the foot.  

I mean, I understand where you're coming from. I can add a more strongly worded note in the admin or in the docs, but really, what's the point of renaming it?
