### ISSUE TITLE
get_user_model - Django 1.4 compatibility

### ISSUE THREAD

**Issue by zerahs** [jleclanche/django-push-notifications#128]
In admin.py, function _user__username is not compatible with Django 1.4

```pytb
File "/push_notifications/admin.py", line 7, in _user__username
     from django.contrib.auth import get_user_model
ImportError: cannot import name get_user_model
```

It can be fixed with something like :
```py
try:
	from django.contrib.auth import get_user_model 
except ImportError: # django < 1.5 
	from django.contrib.auth.models import User
else: User = get_user_model() 
```

**Comment by jleclanche** [comment]
I don't think USERNAME_FIELD exists on Django 1.

**Comment by jleclanche** [comment]
I don't think USERNAME_FIELD exists on Django 1.4 so this would just fail further down.

**Comment by zerahs** [comment]
Yeah you're right, I actually also used <code>return "user__username"</code>

Thanks for the quick fix.
