### ISSUE TITLE
Title in Notifications

### ISSUE THREAD

**Issue by namirsab** [jleclanche/django-push-notifications#131]
Hello!
I was wondering if its possible to add a title to the notifications, because the send_message method only
accepts one message parameter and the extra data.

**Comment by RajatGoyal** [comment]
Yeah, The notifications look really weird without title.

**Comment by stk-13** [comment]
The problem is still not solved?

**Comment by namirsab** [comment]
Yes, sorry. Just add a field called title to The payload.

**Comment by aidan2129** [comment]
+1
