### ISSUE TITLE
Update registration id for an existing record

### ISSUE THREAD

**Issue by devrishik** [jleclanche/django-push-notifications#134]
Initially I was facing [issue 75](https://github.com/jleclanche/django-push-notifications/issues/75) but updating my version from `1.1.0` to `1.2.0` solved
I'm trying to update a `registration_id` for a given `device_id` 
```python
    device, created = GCMDevice.objects.get_or_create(
        device_id=device,
        user=user)
    device.registration_id = gcm
    device.save()
```
If the `device_id` is new then a new record is created successfully, if it is an existing record I get the following error regarding the `device_id`

      File "/Users/..../push_notifications/fields.py", line 57, in get_prep_value
          value = int(value, 16)
      ValueError: invalid literal for int() with base 16: '0xff073c231d204294L'

**Comment by jleclanche** [comment]
Can you try in master?

**Comment by jamaalscarlett** [comment]
I am not seeing this issue with the latest from master.  Tested with the **admin panel** and this block:    

```python
def create(self, request):
    device, created = GCMDevice.objects.get_or_create(device_id=request.data['device_id'])
    device.registration_id = request.data['registration_id']
    device.save()
    if created:
        return Response("Device successfully created! ID: {0}".format(device.device_id))
    else:
        return Response("Device successfully updated! ID: {0} REG_ID: {1}".format(device.device_id, device.registration_id))
```
What value are you passing as a device_id?

**Comment by jleclanche** [comment]
It was fixed then.
