### ISSUE TITLE
Polymorphic models

### ISSUE THREAD

**Issue by eriktelepovsky** [jleclanche/django-push-notifications#140]
Instead of having 2 abstract models, it would be better to have polymorphic structure (using django-polymorphic app for example) or disable Meta attribute abstract in class Device. It is useful in many cases to have ForeignKey to Device object. It is not possible now, is it?

**Comment by matthewh** [comment]
From the django-polymorphic documentation:

> While django-polymorphic makes subclassed models easy to use in Django, we still encourage to use them with caution. Each subclassed model will require Django to perform an INNER JOIN to fetch the model fields from the database. While taking this in mind, there are valid reasons for using subclassed models. That's what this library is designed for!

I would not implement this. The current design is preferred to adding polymorphic support.

**Comment by jleclanche** [comment]
Yeah I forgot to reject this.
