### ISSUE TITLE
Combining both APNS Cert and Private Key?

### ISSUE THREAD

**Issue by leonsas** [jleclanche/django-push-notifications#141]
I'm trying to move from [PyAPNs] (https://github.com/djacobs/PyAPNs) to make it easier to develop push for both Android and iOS.

So far, I haven't been able to send notifications through APNs, although the `.send_message()` methods seems to go through. 
I think the problem is somewhere with the certificate or key.

When using PyAPNs, I would initialize with both my certfile and my private key, e.g:
```
apns = APNs(cert_file="/path/to/cert.pem", key_file="/path/to/key.pem")
```
Here, seems like we only need the `certificate`, which makes me suspicious that the problem might be there.

That said, `d.send_message("Hello world")` completes without any exception, and the Feedback Server contains no errors, so I'm not sure what's causing the problem.

Just to be clear, I can send (and receive onmy phone) notifications using PyAPNs, but haven't been able to do so from this library.

Any thoughts?

**Comment by brad** [comment]
Please refer to [this](https://github.com/jleclanche/django-push-notifications/issues/2) issue for "documentation" on what is required for the certificate/key file. As I think you are suggesting in your title, you do need to use a file that combines the certificate and key. It also must be unencrypted and not password protected.

**Comment by leonsas** [comment]
After more digging, I realized I was trying to test my production app, but from my local console (which defaults to `DEBUG=True`, and so messages were sent to the sandbox APNs, while I was expecting them to arrive at my production app.
