### ISSUE TITLE
How to remove inactive devices?

### ISSUE THREAD

**Issue by pcompassion** [jleclanche/django-push-notifications#142]
This is more of a question.

I suspect there are many inactive users (who uninstalled my app, but account at our server is alive).

Is there a way to exclude those users before sending push notifications?  

-- edit --

I found a section regarding APNS for this.(`python manage.py prune_devices`)  
How about android devices? GCM seems to send `notRegistered` error to notify the server, can we utilize this in any way?

**Comment by jleclanche** [comment]
Looks like there's a way if you contact the feedback server:

http://stackoverflow.com/questions/2362785/howto-remove-device-tokens-received-by-apple-apns-feedback

Then it's a matter of removing the Devices matching that id.

**Comment by pcompassion** [comment]
Thanks jleclanche, I updated my question.

**Comment by jleclanche** [comment]
It's probably possible to add a GCM backend to `prune_devices` yes. Someone would have to do it though; I can't realistically work on this without sponsorship nowadays.

**Comment by pcompassion** [comment]
ok Thank for the response!
