### ISSUE TITLE
'device_id' MySQL max value issue

### ISSUE THREAD

**Issue by ezequielc** [jleclanche/django-push-notifications#147]
I am using Cordova and some device_ids for GCMDevices are above the max value for mysql db big int.
In such case, every device_id is saved as the maximum allowed value (0x7fffffffffffffff).

For instance, I have a device_id='933f14c662228d8a' and it is being stored as 0x7fffffffffffffff.
So, when I try to get my GCMDevice by device_id, I cannot find it.

Any workaround? For a quick fix, I stored the device id as the device name and I am using it as my key.

**Comment by jleclanche** [comment]
That doesn't make sense, it's supposed to be unsigned so the max value should be 2**64

**Comment by ezequielc** [comment]
In my database the column is bigint(20)  (no unsigned):
```
mysql> show columns from push_notifications_gcmdevice;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(11)      | NO   | PRI | NULL    | auto_increment |
| name            | varchar(255) | YES  |     | NULL    |                |
| active          | tinyint(1)   | NO   |     | NULL    |                |
| date_created    | datetime     | YES  |     | NULL    |                |
| device_id       | bigint(20)   | YES  | MUL | NULL    |                |
| registration_id | longtext     | NO   |     | NULL    |                |
| user_id         | int(11)      | YES  | MUL | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
```
Django==1.7.7
MySQL-python==1.2.5
django-push-notifications==1.2.1

**Comment by jleclanche** [comment]
This is the first I hear of this issue. That said I'd highly recommend moving to postgresql...

**Comment by pcsforeducation** [comment]
Similar issue: I'm getting an exception when trying to save a large Android device_id (between 2**63 and 2**64) using SQLite. 

Traceback (most recent call last):
  File "/home/docker/code/push/views.py", line 65, in _register
    device_id=request.data.get('device_id')).save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 963, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.40.0.34/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OverflowError: Python int too large to convert to SQLite INTEGER

**Comment by jleclanche** [comment]
@pcsforeducation What is your backend set to?

**Comment by pcsforeducation** [comment]
@jleclanche django.db.backends.sqlite3. I'm pretty sure this line needs to change to include both (and I would PR it), but even when I do, I still get overflows. I switched my dev env to use MySQL...no problems.

https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/fields.py#L45

**Comment by jleclanche** [comment]
You would get overflows because changing the code also requires you to change the field type in the db.

I'll fix it, but yeah, you should be using postgresql as your db (or mysql if you have to) in production, not sqlite.

**Comment by pcsforeducation** [comment]
Oh I'm definitely not using sqlite in production, just for dev. :)

I made the change locally, deleted the DB, resynced, I get "6|device_id|UNSIGNED BIG INT|0||0" when running "pragma table_info(push_notifications_gcmdevice);" in the dbshell. But I'm still getting overflows for some reason. The device ID I'm trying is '8a8dc609aaaaaaaa' (slightly modified from my actual device). I'll try more tomorrow, maybe it's just late and I'm missing something.

**Comment by shiviser** [comment]
Although this [commit](https://github.com/jazzband/django-push-notifications/commit/0b663a7b93a9afac36654d18fa9c433b1430b301) fixes the type returned by HexIntegerField.db_type from `signed bigint` to `unsigned bigint` for mysql, django does not create any corresponding migration even when I run this -

`python manage.py makemigrations push_notifications`

Is this a django issue/limitation - that django cannot see through such type changes returned by the db_type method of a model field class?

Due to this, I had to manually migrate mysql, which does not seem like a clean solution.

Any comments?
