### ISSUE TITLE
unreliable delivery of push notifications

### ISSUE THREAD

**Issue by rschaniel** [jleclanche/django-push-notifications#149]
Hello,
We run Android and iOS apps where users can subscribe to soccer games and then receive push notifications when a goal is scored. Unfortunately the delivery of the notifications is unreliable. That means, some users get the message for the first goal in a match but not for the second, some users get no messages at all. 
We send the notifications in a model post_save callback. (Is this the right strategy?)

for apns_device in APNSDevice.objects.filter(....):
                    apns_device.send_message(message, extra=data)

We loop through all devices, since the delivery with: 

APNSDevice.objects.filter(....).send_message(...)
(all in one query)

was even worse. 

What is the best strategy to deliver the push notifications reliably? The number of devices is around 20-150 depending on the match. Would a celery task queue help?

**Comment by jleclanche** [comment]
APNS isn't great at reliability; GCM is a lot better. See this article: http://redth.codes/the-problem-with-apples-push-notification-ser/

Generally you want the latter approach, send a whole queryset which will reuse the same socket, much more efficient (making hundreds of connections vs. just making one). But then all notifications are kind of interdependent.

I'd love for someone to implement the technique highlighted in the article. The current one in code isn't great.

**Comment by rschaniel** [comment]
Thank you for the link. I'll see whether I can implement the technique proposed in the article.

In the meantime, I would like to stick to the first approach with looping through the devices and open several connections. A question to this loop approach: Could it be that one send_message() causes an exception and then breaks the loop such the method won't get called on later devices? So could a "try ... except APNSException: continue" help to still be inside the loop and deliver to all valid devices? Sorry I haven't introduced exception logging yet in there.
