### ISSUE TITLE
make migrations shouldn't create migrate files for APNSDevice and GCMDevice

### ISSUE THREAD

**Issue by sainttail** [jleclanche/django-push-notifications#153]
It alter the fields UUID to use models.UUID in both of these models

Shouldn't this done already in Initial migration?

```
dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='device_id',
            field=models.UUIDField(blank=True, help_text=b'UDID / UIDevice.identifierForVendor()', null=True, verbose_name='Device ID', db_index=True),
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='device_id',
            field=push_notifications.fields.HexIntegerField(help_text='ANDROID_ID / TelephonyManager.getDeviceId() (always as hex)', null=True, verbose_name='Device ID', db_index=True, blank=True),
        ),
    ]
```
PS. I install package via pip (1.2.1)

**Comment by Alp-Phone** [comment]
Could you please release 1.2.2 that has the missing migrations in it.  It's hard to deploy 1.2.1 because of those missing migrations.

**Comment by Alp-Phone** [comment]
Actually it's impossible to deploy 1.2.1.

**Comment by jleclanche** [comment]
I don't understand what the issue is.

**Comment by Alp-Phone** [comment]
The currently deployed 1.2.1 version has changes in models.py that are not reflected in the initial migrations file. 
I have a OneToOne relationship to APNSDevice and GCMDevice in one of my own models. This relationship creates a migration dependency to the push_notification app. Hence, when I generate migrations for my own app it also generates a migration inside the push_notification app. That makes deploying 1.2.1 quite cumbersome. 
Does that make sense?  I'm on my phone so excuse my brevity.

**Comment by sainttail** [comment]
Yeah just like @Alp-Phone explain, the current pip version(1.2.1) migration file is still using something like this

```
('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
('name', models.CharField(max_length=255, null=True, verbose_name='Name', blank=True)),
('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date', null=True)),
('device_id', push_notifications.fields.UUIDField(help_text=b'UDID / UIDevice.identifierForVendor()', max_length=32, null=True, verbose_name='Device ID', blank=True)),
('registration_id', models.CharField(unique=True, max_length=64, verbose_name='Registration ID')),
('user', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True))
```
**push_notifications.fields.UUIDField**
so when I type makemigration, it generate another migration file just like the first comment.
But if I clone the current repo instead of installing from pip, there is no problem at all

**Comment by Alp-Phone** [comment]
It would be really, really helpful if you could release a new version to pypi.
Deploying 1.2.1 with migration dependencies in a production environment is a major hassle.
Thank you very much otherwise for this excellent library.

**Comment by Ian-Foote** [comment]
Specifically, the problem is that 8fcc265 is not in [`1.2.1`](https://github.com/jleclanche/django-push-notifications/commits/1.2.1).

**Comment by jamaalscarlett** [comment]
Couldn't you pip install from the repo?

**Comment by Ian-Foote** [comment]
That can be done, but it's much less user-friendly.

**Comment by jleclanche** [comment]
I don't think I'll be releasing a new minor release, I'll just release 1.3.0 in a couple of weeks.

**Comment by Ian-Foote** [comment]
Is there a reason not to release this? From my perspective 1.2.1 is not production quality because of this.

**Comment by jleclanche** [comment]
I'm not available to release anything right now and won't be for a couple of weeks. And since DRF got in, 1.3.0 is releasable, I don't see the point of releasing a 1.2.2.

**Comment by Alp-Phone** [comment]
Can you give us a date when you will be releasing 1.3.0 (a bit more specific than in a couple of weeks)?

**Comment by jleclanche** [comment]
I released it today after all. I'm not a fan of this, I wanted more stuff to land in 1.3 and more time to test it too. But doing a 1.2.2 proved more difficult than I anticipated.

**Comment by Ian-Foote** [comment]
Thank you.

**Comment by jleclanche** [comment]
Had to land a 1.3.1 because of 8f241df5d812a8d43f24d4e226da344f64ef51d6. This is exactly why I didn't want to do this rushed...

**Comment by Alp-Phone** [comment]
I really appreciate what you are doing here.

**Comment by jleclanche** [comment]
Let me know if there's any problem with the 1.3.1 release. If anything comes up though I really won't be available to release anything else until the 8th.

**Comment by Alp-Phone** [comment]
I'll test it today and post some feedback here. Thanks again!

**Comment by Ian-Foote** [comment]
Sorry @jleclanche - I discovered #175.

**Comment by Alp-Phone** [comment]
@jleclanche 
I tested APNS and GCM single and bulk messaging as well as restframework create, delete, update and read operations for CGM and APNS devices.
It's all working for me on python 2.7.
Thanks again and greetings
Moritz
