### ISSUE TITLE
GCM send_message is not working (because using bytes instead of strings?)

### ISSUE THREAD

**Issue by ShadowSpy** [jleclanche/django-push-notifications#166]
Python: 3.4.0
Django: 1.8.1
Django Push Notifications: 1.2.1

When sending a single message using a GCMDevice, I get the error "startswith first arg must be bytes or a tuple of bytes, not str".

When sending a bulk message, I get the error "the JSON object must be str, not 'bytes'".

Both of these errors can be traced back to gcm.py in "_gcm_send_plain" and "_gcm_send_json". 

For _gcm_send_plain, it should probably have "if result.startswith(b"Error="):" on line 75

For _gcm_send_json, it seems that json.loads() is expecting a string rather than bytes.

**Comment by jamaalscarlett** [comment]
Can we see your code that sends the message?

**Comment by jleclanche** [comment]
Try in git, bf3ba928a2abacb987c8cb1affd50aa93267de50 should help and some other commits too.

**Comment by ShadowSpy** [comment]
Looks like b43ba92 has fixed the issue! When is the next version coming out?

As for the code that sends the message, I encountered the error both when trying to use "Send test message" on the Admin panel, and while trying to use the gcmdevice.send_message() function in the Python shell. As an example:

    gcmdevice = GCMDevice.objects.first()
    gcmdevice.send_message('Test message')
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/push_notifications/models.py", line 64, in send_message
        return gcm_send_message(registration_id=self.registration_id, data=data, **kwargs)
      File "/push_notifications/gcm.py", line 123, in gcm_send_message
        _gcm_send_plain(registration_id, *args)
      File "/push_notifications/gcm.py", line 75, in _gcm_send_plain
        if result.startswith("Error="):
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str

The send message in bulk function had similar issues.

**Comment by jleclanche** [comment]
I'll try to release a new version soon.

**Comment by Akatchi** [comment]
Any update on the new version?

**Comment by jleclanche** [comment]
It's out.

**Comment by Akatchi** [comment]
Thanks
