### ISSUE TITLE
Tabs and spaces are mixed, let's choose one !

### ISSUE THREAD

**Issue by ticosax** [jleclanche/django-push-notifications#167]
This project is using sometimes tabs[1] and sometimes spaces[2].
It makes this mix more difficult to contribute.
I propose we adopt only spaces as recommended by pep8
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

[1] https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/models.py
[2] https://github.com/jleclanche/django-push-notifications/blob/master/tests/test_models.py

**Comment by jleclanche** [comment]
[The project uses tabs](https://leclan.ch/tabs). Some files I PR'd in use spaces because I didn't catch it at the time. It can be fixed at any point though so I didn't bother with it yet.

**Comment by ticosax** [comment]
Would be great if you can put a note in the README that points to this article.

**Comment by jleclanche** [comment]
Added contributing guidelines in 1a0a8a536b2b3b22c0669fdefd810a7764553428.

**Comment by ticosax** [comment]
:+1:
