### ISSUE TITLE
GCMDevice.send_message() returns after 2 minutes

### ISSUE THREAD

**Issue by nielsole** [jleclanche/django-push-notifications#169]
Lately I am having issues with sending messages. The call takes about GCMDevice.send_message(mySerializedJsonString) takes about two minutes to complete. 

I debugged it down to(gcm.py):

```
urlopen(request).read()
```

So it really seems Google not responding or the request being somehow wrong. I send about 10 messages / day / device in a test environment (about 2-3 devices). Therefore I assume it can not be the Android throttling.
After urlopen returns, the message is delivered almost instantly.

Is anyone else experiencing this issue? Does someone have any idea how to debug this further? 
I am on 1.2.1

**Comment by jleclanche** [comment]
Closing old unanswered questions.
