### ISSUE TITLE
New APNS API announced at WWDC 2015

### ISSUE THREAD

**Issue by chrisballinger** [jleclanche/django-push-notifications#170]
Just a FYI there will be a big change in APNS soon: https://developer.apple.com/videos/wwdc/2015/?id=720

The new API is way cleaner, backwards compatible, and fixes a lot of the flaws from the original design (especially error handling).

**Comment by jleclanche** [comment]
Sounds great.

**Comment by Alp-Phone** [comment]
The relevant talk starts at 16:45 minutes.
Thanks for the link, it looks like it'll fix all our current problems :)

**Comment by imkevinxu** [comment]
Is there any work being done in prep for the new APNS API?

**Comment by jleclanche** [comment]
Not from me, but I'm welcome to PRs.

**Comment by Alp-Phone** [comment]
I haven't started working on this either.  Is there a release date?
I do want to be involved so if somebody is planning to work on this feature, give me a ping.

**Comment by jleclanche** [comment]
Subscribe to this issue, this will be the tracker for it.

**Comment by Alp-Phone** [comment]
Done

**Comment by koutoftimer** [comment]
@Proper-Job there are a lot of work to do. 
First of all, I would like to move all code related to sending push notifications to external library like [apns-client](https://bitbucket.org/sardarnl/apns-client) and [gcm-cliend](https://bitbucket.org/sardarnl/gcm-client/). I'm not saying they are perfect solutions, I'll do some research on this topic.

@jleclanche nothing personal, but I think it is better to develop libraries that can handle sending push notifications for everybody who use python, and then use them for building library for django notifications.

**Comment by Proper-Job** [comment]
@koutoftimer If you need an extra pair of eyes, I'll be happy to review changes.

**Comment by jleclanche** [comment]
> I think it is better to develop libraries that can handle sending push notifications for everybody who use python, and then use them for building library for django notifications.

I'm in favour of that approach, but when I created this library there was nothing like that then. I'll be happy to discuss this further later.

**Comment by jleclanche** [comment]
PyAPNS2 takes care of this.
