### ISSUE TITLE
Its Possible Config 2 .Pem Files for APNS

### ISSUE THREAD

**Issue by coffe67** [jleclanche/django-push-notifications#172]
Hi, my question is can i configure 2 pem files in the settings configs? , I have 2 mobile apps one for customers and other for employees, boot apps consume an API from the same Django Project, the thing is that for every one Mobile App is required an unique .pem file, but base on your configuration  it's not possible setup more than one .pem file.

Could you give me a suggestion about it?

# Push Notifications Conf
PUSH_NOTIFICATIONS_SETTINGS = {
    "APNS_CERTIFICATE": STATIC_ROOT+"/PEMFILEAPP1.pem"
}

**Comment by jleclanche** [comment]
No, sorry, see #130
