### ISSUE TITLE
APNS Queryset bulk push not delivering to all

### ISSUE THREAD

**Issue by somghosh** [jleclanche/django-push-notifications#173]
I am trying to send bulk push to an APNS queryset

I have around 10 APNS devices in the database, of which 6 are valid ('pushable') and the rest are probably invalid (no way for me to check I think)

### iOS Code

	users = User.objects.filter(is_staff=True)

	ios_device_qs = APNSDevice.objects.filter(user__in=users)
	for x in ios_device_qs:		#around 10 devices 
	    x.send_message("ios push test sent one by one")		#this one gets sent to all
	
	
	ios_device_qs.send_message("ios push bulk push")		#this one does not reach all, but reaches few

There might be a few bad registration ids in the ios_device_qs list. However, I don't get any error in the bulk push function - it returns silently, and I can see that only some of the phones receive the push in reality. 

Interestingly when I do the corresponding thing on Android, i get :

### Android code

	android_device_qs = GCMDevice.objects.filter(user__in=users)
    android_device_qs.send_message(android_text)
	

Gives me the a nice status report and causes an exception, which I think I need to handle in a try catch block (as it causes an exception)

### status

	{
	 u'failure': 1,
	 u'canonical_ids': 1,
	 u'success': 3,
	 u'multicast_id': 8877687881611973820,
	 u'results': [
	   {
	     u'registration_id': u'APA91bHxOQ9SSPIEKbUPSvt5XCafaA07ZKyrWPWbqmyCWU0vZz7XkR8ATl6TjTRbfW3mtPLLCq5ozsjK48outmJviekVIbVTQrNTz-uyatxtnB5kFekLDSCz7ueFPLp4NzIzguRXHNOzKxP9Ned2e48vb0DnveQCYg',
	     u'message_id': u'0:1435526571558404%a4059e11f9fd7ecd'
	   },
	   {
	     u'error': u'MismatchSenderId'
	   },
	   {
	     u'message_id': u'0:1435526571558483%a4059e11f9fd7ecd'
	   },
	   {
	     u'message_id': u'0:1435526571557826%a4059e11f9fd7ecd'
	   }
	 ]
	}

**Comment by Alp-Phone** [comment]
The [documentation] (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW1) states that 
``If you send a notification that is malformed or otherwise unintelligible, APNs returns an error-response packet and closes the connection.``
If you know that there are invalid tokens in your database, clean them up using the feedback service. Otherwise, if say token number 6 in your bulk message is invalid, tokens 7-10 don't get sent.

**Comment by jimmykobe1171** [comment]
The APNS protocol is just a shit, If you fail on one token, all tokens after the failed token will not be push successfully. So write some logic to check this failure and resend remaining tokens after the failed token.

**Comment by Alp-Phone** [comment]
Or wait until the new api launches. https://github.com/jleclanche/django-push-notifications/issues/170

**Comment by jleclanche** [comment]
Yeah I think waiting for the new API is best. Closing as dup of #122
