### ISSUE TITLE
django.db.migrations.graph.NodeNotFoundError on Heroku deployment 

### ISSUE THREAD

**Issue by mhb11** [jleclanche/django-push-notifications#174]
Hi Jerome, 

Great library - precisely what I needed. Really glad I found it, but running into an issue for the past couple of days that I'm unable to solve. So I'm escalating it to you. 

I have a very simple models.py (below). Everything is properly indented, don't worry. 
```py
from django.db import models
from push_notifications.models import GCMDevice
from django.core.urlresolvers import reverse
class DeviceObj(GCMDevice):
	def get_absolute_url(self):
		return reverse('success')
```
Views.py:
```py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from .models import DeviceObj
from .forms import DeviceForm
class DeviceCreateView(CreateView):
	model = DeviceObj 
	form_class = DeviceForm
```
Forms.py:
```py
from django import forms
from .models import DeviceObj
class DeviceForm(forms.ModelForm):
    class Meta:
        model = DeviceObj
        fields = ('registration_id',)
```
When I load this on my heroku app and run syncdb, I get the following error:

django.db.migrations.graph.NodeNotFoundError: Migration custompusher.0001_initial dependencies reference nonexistent parent node (u'push_notifications', u'0002_auto_20150629_1438')

Interestingly, it runs fine locally. It's a very simply set up - I just wanted to test your library, but can't get past this fundamental hurdle. Can you should some light on this?

**Comment by mhb11** [comment]
I'm on Django 1.8, DB is postgres

**Comment by jleclanche** [comment]
`0002_auto_20150629_1438` is an autogenerated parent node. Are you copying/importing the db somehow?

Did you try in git?

**Comment by Alp-Phone** [comment]
It's what we've been saying in https://github.com/jleclanche/django-push-notifications/issues/153#issuecomment-116966024.

1.2.1 is broken on PyPi. You have to make a source install that includes https://github.com/jleclanche/django-push-notifications/commit/8fcc265331605241a538ebc571dac912d08f2f9f

**Comment by jleclanche** [comment]
It doesn't look like the same issue.

**Comment by Alp-Phone** [comment]
It does to me. If you look at the error message:
``django.db.migrations.graph.NodeNotFoundError: Migration custompusher.0001_initial dependencies reference nonexistent parent node (u'push_notifications', u'0002_auto_20150629_1438')``
That means that locally there was a migration dependency created in one of his own apps that references the push_notifications app.  So locally the migration dependency is there.
But it's not there when you install the package on Heroku using pip.  Hence the error.

**Comment by jleclanche** [comment]
Ok, against my better judgement I'll do a 1.3 release today.

**Comment by jleclanche** [comment]
Closing as dup of #153
