### ISSUE TITLE
Makemigrations creates a new migration when running python 3

### ISSUE THREAD

**Issue by Ian-Foote** [jleclanche/django-push-notifications#175]
Running `python manage.py makemigrations` on a python 3 project creates the following migration:

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import push_notifications.fields


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='device_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Device ID', help_text='UDID / UIDevice.identifierForVendor()', db_index=True),
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='device_id',
            field=push_notifications.fields.HexIntegerField(blank=True, verbose_name='Device ID', help_text='ANDROID_ID / TelephonyManager.getDeviceId() (always as hex)', null=True, db_index=True),
        ),
    ]
```

This does not happen on python 2.

I suspect this is caused by the presence of `bytes` in the [initial migration](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/migrations/0001_initial.py#L23) (and [here](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/migrations/0001_initial.py#L39)).

**Comment by Ian-Foote** [comment]
I think just adding the new migration will fix this and work correctly on both python versions.

**Comment by Bartvds** [comment]
I also experience this issue (and #153). Did you find a workaround? 

I'm on `1.3.1` from pip (on python 3.4 and django 1.8.3)

**Comment by Bartvds** [comment]
I found a simple workaround: in my own migrations I just edited the dependency on `push_messages` to point to the `0001_initial` file. 

Seems to work so far on our test rig; still a real solution would be appreciated.

**Comment by jleclanche** [comment]
PRs welcome for the correct fix; I don't have a real world instance to test this on.

**Comment by Ian-Foote** [comment]
Is there a problem with my proposed #176?

**Comment by Bartvds** [comment]
I think adding @Ian-Foote's migration to the release would be the correct fix.

**Comment by BudgieInWA** [comment]
I believe this is no longer an issue since #222.
