### ISSUE TITLE
AttributeError  in models.py for device_id

### ISSUE THREAD

**Issue by shivi74** [jleclanche/django-push-notifications#177]
I installed this package like yesterday and it worked fine but when I do it again today it throws me an error for device_id field in models.py with UUIDField.

AttributeError: 'module' object has no attribute 'UUIDField'

Well I think the issue is with latest release. FYI

What should I do now?

**Comment by jleclanche** [comment]
What version of Django do you run?

**Comment by shivi74** [comment]
1.7

**Comment by jleclanche** [comment]
Django 1.8 is required as of 1.3.0. Support for 1.7 is available in 1.2.1.
