### ISSUE TITLE
ImportError: No module named uuidfield

### ISSUE THREAD

**Issue by aTylerRice** [jleclanche/django-push-notifications#183]
I'm on version 1.7 django and version 1.2.1 of django-push-notifications

I'm getting this error 

>>> from push_notifications.models import APNSDevice
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/models.py", line 4, in <module>
    from .fields import HexIntegerField, UUIDField
  File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/fields.py", line 20, in <module>
    from uuidfield import UUIDField
ImportError: No module named uuidfield

I ran python manage.py makemigrations first then I ran python manage.py migrate and I still get this error.

**Comment by jleclanche** [comment]
You can try version 1.2.0 instead. Apparently 1.2.1 didn't work too well. If it becomes a common issue I'll try again to release an 1.2.2 seeing as 1.3 drops Django 1.7 support.

**Comment by aTylerRice** [comment]
thanks for the help! still the same problem unfortunately probably going to have to go with a different solution even though i've use this library before, on a very tight deadline

**Comment by jleclanche** [comment]
Did you make sure to install django-uuidfield as per the requirements?

**Comment by jleclanche** [comment]
BTW if you're able to develop on Django 1.8, 1.3 release will solve your problem entirely.

**Comment by aTylerRice** [comment]
yeh forgot to install it... stupid mistake... thanks! and yeh we will be updating to 1.8 but we are launching in two weeks so after that thats the plan

**Comment by jleclanche** [comment]
Good luck.
