### ISSUE TITLE
Unable to pass device_id as a POST parameter when testing GCMDevice object creation

### ISSUE THREAD

**Issue by mhb11** [jleclanche/django-push-notifications#187]
I'm testing this library using an HTTP Request plug-in for Mozilla (HttpRequester). It works perfectly if I POST to my URL as follows:
csrfmiddlewaretoken=foobar&registration_id=foo

But it never works if I do:
csrfmiddlewaretoken=foobar&registration_id=foo&device_id=1234abcd 
Note: I always ensure device_id being POSTED is hex. 

I can't seem to guess why the latter case doesn't work while the former works impeccably. Any leads why your library functions like so?

**Comment by mhb11** [comment]
My template is pretty bare bones:
<form method="POST" action="{% url 'registration_id' %}">
{% csrf_token %}
<input type="hidden" name="registration_id" value="{{ registration_id }}">
<input type="hidden" name="device_id" value="{{ device_id }}">
</form>

So is forms.py:
class DeviceForm(forms.ModelForm):
    class Meta:
        model = GCMDevice
        fields = ('registration_id','device_id')

**Comment by mhb11** [comment]
I'm using a simple template to test this:

<form method="POST" action="{% url 'registration_id' %}">
{% csrf_token %}
<input name="registration_id" value="{{ registration_id }}">
<input name="device_id" value="{{ device_id }}">
<button>Submit</button>
</form>

**Comment by jamaalscarlett** [comment]
What error are you receiving?

**Comment by mhb11** [comment]
The template merely reloads, no error is thrown (debug is set to TRUE btw).

**Comment by jamaalscarlett** [comment]
Can you post the code from views.py that processes the request?

**Comment by mhb11** [comment]
Sure. In case the code doesn't format here properly, the views.py can be seen in this SO question here: http://stackoverflow.com/questions/31536908/unable-to-pass-multiple-post-parameters-from-django-template
Conversely you can view it here too: https://github.com/mhb11/messaging/blob/master/custompusher/views.py#L9

**Comment by jamaalscarlett** [comment]
Please try https://github.com/jamaalscarlett/django-push-notifications/tree/bug_update

**Comment by jleclanche** [comment]
fixed by #189, dup of #171

**Comment by mhb11** [comment]
Thanks! Will this work if the Android_ID received is erroneously not HEX?

**Comment by jleclanche** [comment]
not sure, but you can filter that at the app level, not send the id if it doesnt look right.

**Comment by mhb11** [comment]
I was thinking we ought to patch out that too, but yea I suppose the client can take care of it on its end.

**Comment by jamaalscarlett** [comment]
If will fail if the id is not an integer or hex.

**Comment by mhb11** [comment]
Yea, saw that when testing with a non-HEX string for robustness.

**Comment by jamaalscarlett** [comment]
I agree with jleclanche, that validation should be handled by your app.

**Comment by jleclanche** [comment]
As long as django-push-notifications doesn't crash then it definitely should be app-level validation.
