### ISSUE TITLE
Can't send with "extra"

### ISSUE THREAD

**Issue by gulfpearl** [jleclanche/django-push-notifications#188]
Hi, I don't think I'm understanding this properly, 

when I send a message for both ios and gcm I do the following using send_message of APNSDevice and GCMDevice:

```
send_message(None, extra={'from':_from, 'channel':_channel, 'message':_message})
```

The variables in the dictionary are just small strings. 

For GCM, I receive a 400 response and for APNS, it just sends an empty push notification to the client without these keys being captured and pushed to the client. 

What am I doing wrong? Thanks in advance.

**Comment by gulfpearl** [comment]
On the client side, this is what I receive {"event":"message", ..., "payload":{}}.

If I'm doing it wrong then the docs arent' really clear on how to set the "extra" and its purpose. Should the payload be populated by extra?

**Comment by kaushik-zapyle** [comment]
Did you figure out? how do I pass the content-available as true?

**Comment by Alp-Phone** [comment]
Could you maybe state what you are trying to achieve?
Are you simply trying to send a APNS and GCM message?  You don't need the extra kwarg for that, you can just go:

```python
GCMDevice.send_message({'from':_from, 'channel':_channel, 'message':_message})
```

For APNS you need to format your payload according to [specification](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1), naturally. Probably something like this:

```python
APNSDevice.send_message({'title':'Hello','body':'World'}, sound='default')
```
