### ISSUE TITLE
Error in GCMDeviceAdmin

### ISSUE THREAD

**Issue by alfaro28** [jleclanche/django-push-notifications#192]
I was trying to edit some GCMDevices in the admin but I was getting the exception

    hex() argument can't be converted to hex
    at push_notifications/admin.py in device_id_hex, line 66

I think this was an issue because my device_id was NULL, I think a simple null check would solve the issue.

My temporary fix was to put this in my own admin.py file:

    admin.site.unregister(GCMDevice)
    admin.site.register(GCMDevice, DeviceAdmin)

**Comment by jamaalscarlett** [comment]
When you say NULL, do you mean that you saved a device with no device_id set?  That should not thrown an exception, what version are you running?

**Comment by alfaro28** [comment]
Yes, the device_id was null on my mysql db, I'm running 1.3.1 with django 1.8.2

**Comment by jamaalscarlett** [comment]
Try this branch, it should be fixed.  https://github.com/jamaalscarlett/django-push-notifications/tree/bug_device_id_null

**Comment by ekonstantinidis** [comment]
I'm having exactly the same issue.. The error i'm getting:

    TypeError at /admin/push_notifications/gcmdevice/
    hex() argument can't be converted to hex
    Request Method:	GET
    Request URL:	http://192.168.1.79:60773/admin/push_notifications/gcmdevice/
    Django Version:	1.8.3
    Exception Type:	TypeError
    Exception Value:	 hex() argument can't be converted to hex

**Comment by jamaalscarlett** [comment]
Have you tried the pull request code?

**Comment by ekonstantinidis** [comment]
@jamaalscarlett I've just tried it and it works! It would be awesome if it was merged :+1:

**Comment by jamaalscarlett** [comment]
I addressed one issue jleclanche had, so hopefully soon.

**Comment by jleclanche** [comment]
Landed.

**Comment by ekonstantinidis** [comment]
Amazing! Thanks @jleclanche for merging and for django-push-notifications! It is awesome! Is there an estimation for a new release?

**Comment by jleclanche** [comment]
I've considered making a new release now but I'm giving it more time to see if more bugfixes can land.

**Comment by tasn** [comment]
Hey, any plan for a release? It's been a while, and this bug is pretty annoying. :)

Thanks.

**Comment by jleclanche** [comment]
Ill try to do a release after the current blocked pr lands.

**Comment by tasn** [comment]
Thanks.
