### ISSUE TITLE
No exception, but no notification pushed to iOS device

### ISSUE THREAD

**Issue by scotu** [jleclanche/django-push-notifications#194]
Hello, I need some help on how to debug this issue. I tried sending bulk and single notifications (and also sending test from the admin panel)

```
> from push_notifications.models import APNSDevice
> APNSDevice.objects.get(user=14).send_message("Test")
> APNSDevice.objects.filter(user=14).send_message("Test2")
```

I read another issue ( https://github.com/jleclanche/django-push-notifications/issues/95 ) where APNS requires APNS_ERROR_TIMEOUT to be set (I did `APNS_ERROR_TIMEOUT = float("0.5")`) to receive errors but I don't see any error. 

The certificate is in the right path because before setting the library was complaining about it. The iOS app can receive notification sent with a ruby command line tool the iOS developer showed me ( https://github.com/nomad/houston )

I'm not sure of any detail you need to help me debug, but just let me know, I'll provide them

this are the settings I have:

```
PUSH_NOTIFICATIONS_SETTINGS = {
    "GCM_API_KEY": "",
    "APNS_CERTIFICATE": "/home/ubuntu/path-to.pem",
    "APNS_CA_CERTIFICATES": "/etc/ssl/certs/path-to-entrustca.pem",
    "APNS_ERROR_TIMEOUT": float("0.5")
}
```

Thanks

**Comment by Alp-Phone** [comment]
As far as I know the current APNS API implementation has no sensible error handling mechanism.
That would be why you aren't seeing any errors.
Possible things to go wrong here are:
- Are you sending a development device token to the production environment or vice versa?
- Can you connect to the APNS server? ``openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert path/to/cert.pem -key path/to/key.pem``
- Have you enabled notifications on your client device?
- You might want to add sound='default' as a kwarg for the extra umph
- Is your firewall blocking any ports?

The library definitely sends out messages when properly configured.

**Comment by scotu** [comment]
thanks for the reply @Alp-Phone 

* I tried both sandbox and production
* the openssl command doesn't give me errors as far as I can see (but there is a lot of output). The difference between calling the command for gateway.sandbox.push.apple.com vs gateway.push.apple.com is that "sandbox" does not release the command at the end (I need to control-c) while gateway.push.apple.com releases.
* the notification should be enabled as I'm correctly receiving them for the same registration_id when sent using https://github.com/nomad/houston 
* I'll try to add the sound
* I'm in aws ec2, do you know what ports should be opened? this might be the issue as the security groups (aws firewall) are pretty strict 

Regarding sending through the admin: single notification doesn't provide a success message or an error one, while the bulk does show a green "success message" that say: "All messages were sent: None" (I suppose the "None" is not a good sign :D )

Thanks again

**Comment by Alp-Phone** [comment]
My guess would be the firewall ports.  APNS communicates on 2195 and 2196.

**Comment by scotu** [comment]
the outbound ports are open, I opened the inbound (but I have the feeling communication is outbound from my server, not inbound); I also tried with sound, but same result (no notification).

**Comment by scotu** [comment]
Push working now! Thanks
