### ISSUE TITLE
postgres: required argument is not an integer

### ISSUE THREAD

**Issue by dmr** [jleclanche/django-push-notifications#199]
We were using django-push-notifications for a few months now and now I wanted to dump my database data and I get an error.
We recently switched to postgres, maybe that is the issue.

Turns out the command 

    from push_notifications.models import GCMDevice
    GCMDevice.objects.all()

is causing this error

```
site-packages/push_notifications/fields.py in to_python(self, value)
     72                 # on postgres only, re-interpret from signed to unsigned
     73                 if connection.settings_dict["ENGINE"] in postgres_engines:
---> 74                         value = hex(struct.unpack("Q", struct.pack("q", value))[0])
     75                 return value
     76 

error: required argument is not an integer
```

Can anybody help me?

**Comment by jleclanche** [comment]
The db_type of HexIntegerField changes between db engines, see:

**Comment by jleclanche** [comment]
https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/fields.py#L48-L55

**Comment by dmr** [comment]
Thanks for the quick reply.

This means I cannot just migrate my tables. Instead I have to ./migrate dumpdata and loaddata instead, do I read correctly?

**Comment by jleclanche** [comment]
I'm not sure actually, but the easiest thing is to migrate your tables as normal, and once they are on postgres, post-process the GCMDevice.device_id column.

**Comment by dmr** [comment]
The problem is that I get import errors if I just migrate.
I think I'll delete the GCMDevice and reregister them. The app has less than 1000 installs :)

**Comment by jleclanche** [comment]
Sure thing.
