### ISSUE TITLE
Adding Payload

### ISSUE THREAD

**Issue by kaushik-zapyle** [jleclanche/django-push-notifications#200]
How to add payload of content-available?

**Comment by kaushik-zapyle** [comment]
Also how do I remove the default collapse_key?

**Comment by Alp-Phone** [comment]
I assume you're talking about APNS

>How to add payload of content-available?

Have you tried 
```python
apns_send_message(reg_id, None, content_available=True)
apns_send_bulk_message(reg_id, None, content_available=True)
```
>Also how do I remove the default collapse_key?

Where/what is that?

**Comment by jamaalscarlett** [comment]
If you  are talking about the collapse_key in gcm, you would send it as a kwarg in send_message()

**Comment by abhirocks9636** [comment]
sir, i have created separate field for sending notification,there is only two field TITLE and MESSAGE
and i don't understand how to send .....plzzzz help(my test notification connection is successful )

**Comment by jamaalscarlett** [comment]
@abhirocks9636  Can you post your code?

**Comment by abhirocks9636** [comment]
if request.method == 'POST':
       notification = Notification.objects.all()
       serializer = NotificationSerializer(notification, many=True)
       serializer = NotificationSerializer( data=request.data)
     #  device = GCMDevice.objects.get(registration_id=gcm_reg_id)
     #  device.send_message(alert)
     #  device = APNSDevice.objects.get(registration_id=apns_token)
     #  device.send_message(alert)
def send_message(alert):
    devices = GCMDevice.objects.filter(user__first_name="admin")
    devices.send_message(alert)
         # data.encode("base64")
       if serializer.is_valid():
           serializer.save()
           res_msg = {'Success_Message' : 'Successful','Success_Code' : 200}
           return Response(res_msg)
       else:
           return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

**Comment by abhirocks9636** [comment]
here i created a variable ''alert'' which contain 'title' and 'message' and i want to pass this alert variable to device.send_message() as parameter .
plzz help
thanks

**Comment by abhirocks9636** [comment]
how to call device.send_message() in another view and send notification .(New django Learner)
any help would be appreciated 
thank you

**Comment by Proper-Job** [comment]
Have you tried doing something like this:

```python
from push_notifications.apns import apns_send_bulk_message, apns_send_message
from push_notifications.gcm import gcm_send_bulk_message, gcm_send_message

FOUR_WEEKS = 60 * 60 * 24 * 7 * 4
time_to_live = FOUR_WEEKS
data = {
    'title': 'Title',
    'body': 'Body',
}
#  bulk
gcm_send_bulk_message(['id_1', 'id_2'], data, time_to_live=time_to_live)
apns_send_bulk_message(['id_1', 'id_2'], data, sound='default')

#  or single
apns_send_message('id', data, sound='default')
gcm_send_message('id', data)
```

**Comment by abhirocks9636** [comment]
thank you sir,it is working but
i have to send notification simultaneously to gcm and apns to all the registered device.
![screenshot from 2015-09-21 18 17 11](https://cloud.githubusercontent.com/assets/14234790/9992160/b6fa6514-608d-11e5-8167-4b02384cb020.png)

**Comment by Proper-Job** [comment]
Ok, then just do the bulk method:
```python
gcm_send_bulk_message(['id_1', 'id_2'], data, time_to_live=time_to_live)
apns_send_bulk_message(['id_1', 'id_2'], data, sound='default')
```

**Comment by abhirocks9636** [comment]
thank you very much sir,
 I will let you know further

**Comment by abhirocks9636** [comment]
Its working fine from shell but when I'm trying same with my views.py nothing happens. 
Please help me out.

**Comment by Proper-Job** [comment]
Look, I don't really know what to tell you.
You've pasted unformatted code.  Perhaps you could create a gist or pastebin so we can actually look at your code.
Perhaps the queryset is empty?  Perhaps the form is not valid?
At this point, now that you have it working in the Django shell it's really not a library issue is it?
Perhaps it's a general Python problem?  Perhaps there is another forum more suited for those questions?

**Comment by abhirocks9636** [comment]
how to change device registration response code for gcm and apns??
plzzz guide

**Comment by Proper-Job** [comment]
Can you be more specific?

**Comment by abhirocks9636** [comment]
when i try to register my android device....to http://host/device/gcm ...i got the same response what i post(such as:name,registration_id,device_id,active) but not able to register my device.
device registration from admin and manual post is working fine.

**Comment by Proper-Job** [comment]
I think this might be related https://github.com/jleclanche/django-push-notifications/issues/201

**Comment by Abondened** [comment]
My problem is somewhere similar to @abhirocks9636. I'm using django-push-notification and able to register my device from admin as well as web-service but when I'm trying to do same from my code it is neither reflecting on my admin panel nor in db 
db used - mysql  
thanks for help.

**Comment by jamaalscarlett** [comment]
@Proper-Job is right, the issue was a bug in the last official release.  If you pull down the code from master and build/install it yourself, it should be fixed.

**Comment by Abondened** [comment]
Now I'm getting this error
^admin/
^ ^$ [name='api-root']
^ ^\.(?P<format>[a-z0-9]+)/?$ [name='api-root']
^ ^device/apns//$ [name='apnsdevice-list']
^ ^device/apns\.(?P<format>[a-z0-9]+)/?$ [name='apnsdevice-list']
^ ^device/apns//(?P<registration_id>[^/.]+)/$ [name='apnsdevice-detail']
^ ^device/apns//(?P<registration_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$ [name='apnsdevice-detail']
^ ^device/gcm//$ [name='gcmdevice-list']
^ ^device/gcm\.(?P<format>[a-z0-9]+)/?$ [name='gcmdevice-list']
^ ^device/gcm//(?P<registration_id>[^/.]+)/$ [name='gcmdevice-detail']
^ ^device/gcm//(?P<registration_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$ [name='gcmdevice-detail']
current URL, device/gcm/, didn't match any of these.

**Comment by abhirocks9636** [comment]
thank you sir, i appreciate your help

On Mon, Sep 28, 2015 at 7:11 PM, Abondened <notifications@github.com> wrote:

> Now I'm getting this error
> ^admin/
> ^ ^$ [name='api-root']
> ^ ^.(?P[a-z0-9]+)/?$ [name='api-root']
> ^ ^device/apns//$ [name='apnsdevice-list']
> ^ ^device/apns.(?P[a-z0-9]+)/?$ [name='apnsdevice-list']
> ^ ^device/apns//(?P[^/.]+)/$ [name='apnsdevice-detail']
> ^ ^device/apns//(?P[^/.]+).(?P[a-z0-9]+)/?$ [name='apnsdevice-detail']
> ^ ^device/gcm//$ [name='gcmdevice-list']
> ^ ^device/gcm.(?P[a-z0-9]+)/?$ [name='gcmdevice-list']
> ^ ^device/gcm//(?P[^/.]+)/$ [name='gcmdevice-detail']
> ^ ^device/gcm//(?P[^/.]+).(?P[a-z0-9]+)/?$ [name='gcmdevice-detail']
> current URL, device/gcm/, didn't match any of these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jleclanche/django-push-notifications/issues/200#issuecomment-143746356>
> .
>



-- 
@bh!

**Comment by jamaalscarlett** [comment]
@abhirocks9636 did the latest code from master fix the issue?

**Comment by abhirocks9636** [comment]
yes sir

**Comment by jamaalscarlett** [comment]
@kaushik-zapyle did @Proper-Job's suggestion fix your issue?

**Comment by tonazih** [comment]
I am using GCM with over APN. and I need to set the content_available= true 
I tried return _gcm_send_json(registration_ids, data, content_available=1), and I get
" HTTP Error 400: Bad Request"
I did test with curl and it is working fine. 
here is the curl I send.
curl --header "Authorization: key=xxxxxxxxx" --header Content-Type:"application/json" https://android.googleapis.com/gcm/send
 -d "{\"to\":\"xxxxxxxxxx\",\"content_available\":true,\"notification\":{\"body\":\"Hello from GCM\"}}"

If I add content-available (- not _) it does not complain however it does not wake up the iOS application.

**Comment by tonazih** [comment]
Never Mind I found the fix, Use True (not 1)
gcm_send_json(registration_id, data, content_available=True)
