### ISSUE TITLE
integer out of range for 'q' format code

### ISSUE THREAD

**Issue by xleon** [jleclanche/django-push-notifications#202]
error at /device/gcm/
integer out of range for 'q' format code
Request Method:	POST
Request URL:	http://127.0.0.1:8000/device/gcm/
Django Version:	1.8.3
Exception Type:	error
Exception Value:	
integer out of range for 'q' format code
Exception Location:	/Users/xleon/VirtualEnvs/Sclusib/lib/python2.7/site-packages/push_notifications/fields.py in to_python, line 74

**The line 74:**
value = hex(struct.unpack("Q", struct.pack("q", value))[0]) # value == 12593930652737385865

**The data I´m sending:**
{
    "name": "whatever",
    "active": true,
    "device_id": "aec6a1340250b589",
    "registration_id": "APA91bFNBpRZB4EjilDLVTfqz9b9u1Sd748Rej8c9nyTRZ8WRxTbNSVZZeXYoSsEFa9hmpG48MDGeZ0pidbtDk0Dgj2VQ0PmxEDnRyhG13qAnUtAuIrCW_utTXTnqQNwyvV5vlI7-7by"
}

**Comment by xleon** [comment]
Fixed! It seams that device_id value sent from Android was wrong (not the actual id I think)

**Comment by aeikenberry** [comment]
@xleon Could you go into more detail how this was resolved? I'm having this issue as well.

**Comment by xleon** [comment]
It was simple. I was sending a wrong device id from Android. It´s not an issue related to django-push-notifications. Double check you are sending the correct device id from Android
