### ISSUE TITLE
1.2.1 + python3, error 

### ISSUE THREAD

**Issue by pcompassion** [jleclanche/django-push-notifications#203]
http://stackoverflow.com/questions/30268680/typeerror-during-send-message-in-django-push-notifications-1-2-1-python-3-4-dj

I have the same problem.

**Comment by jleclanche** [comment]
Please use the most recent release of Django Push Notifications.

**Comment by pcompassion** [comment]
most recent release requires django 1.8? how about django < 1.8?

**Comment by jleclanche** [comment]
I decided not to support django <= 1.7 in the 1.3 branch, yes. If you want Python 3 support you should be using django 1.8 anyway.

**Comment by pcompassion** [comment]
oh didn't know python 3 requires 1.8. Thanks for reply.

**Comment by jleclanche** [comment]
I believe it works fine in 1.7 but there were fixes in 1.8 too.

**Comment by pcompassion** [comment]
I'm using 1.7.7
