### ISSUE TITLE
Please read: Looking for volunteers to co-maintain this project

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/django-push-notifications#205]
If you want to get commit access to this project please express your interest here. I no longer use django-push-notifications myself but I don't want to see it rot away.

I however ask that you maintain a very high standard for the code that goes in and [not change the coding or commit style](https://github.com/jleclanche/django-push-notifications/blob/1a0a8a536b2b3b22c0669fdefd810a7764553428/CONTRIBUTING.md).

I will only consider developers who have already contributed to the project, or can prove in some way that they are very familiar with the codebase.

This won't be completely hands-off, I will remain available to help for releases and chime in for decisions.

**Comment by Alp-Phone** [comment]
Hi Jerome
I'd be willing to help. I've got this project actively deployed and I'm interested in keeping it alive and healthy.  I'd especially like to see it integrate the upcoming Apple specifications.
I see myself helping out in the triage stage for tickets and coding bug fixes and coding the aforementioned feature.  I wouldn't want to be the only maintainer, but I'm committed to pitch in and keep this project going.
Greetings
Moritz

**Comment by jamaalscarlett** [comment]
I am also willing to help maintain the project.  I am using it currently on
the gcm side, but I would love to help.

Jamaal

**Comment by koutoftimer** [comment]
I'd like to help. I read everything except `api.tastypie` module, `models` and `api.rest_frameworks` a lot of times, because it is what I need right now.

I faced with push notifications today and found this application, which seems good, but not really. Actually I was expecting more flexibility to extend models and override views, serializers.

**Comment by jleclanche** [comment]
@matthewh are you interested in maintaining the APNS part of the project?

**Comment by masnun** [comment]
Hi, 

I am using the project in several of my apps and it's very important for me that the project remains alive. I work closely with a mobile development shop and the push notifications are usually always used in our products. 

I will admit that I am not very familiar with it's internals and not ready to become a maintainer. So as a step forward, I will go through the issues and try to come up with some PRs. Once I feel confident enough about the codebase, I will be happy to help. 

Thanks for the package and all the efforts you have put into it over the years.

**Comment by jleclanche** [comment]
@masnun Thanks! Your help will be appreciated.

**Comment by jamaalscarlett** [comment]
👍

**Comment by jleclanche** [comment]
@Proper-Job @masnun @koutoftimer Hey guys, are you still interested in helping out?

**Comment by koutoftimer** [comment]
I'm out of sync with the code more than a year. Have to analyze changes first.

**Comment by Proper-Job** [comment]
@jleclanche yes, in a limited capacity, I'm willing to help out.
Has anything changed in the maintainer setup recently?  Do you and @jamaalscarlett still do the heavy lifting? What would you have me do ideally?  Triage of tickets? Or help on specific issues?

**Comment by jleclanche** [comment]
Ticket triage is okay, because most are questions and they tend to get answered. I can also keep an eye on them.

Here are the main things that need to happen:

* Redesign & rework of the apns backend so that it uses [PyAPNS](https://github.com/djacobs/PyAPNs) or a similarly-suitable library.
* Landing support for multiple mobile apps (#348). The PR in question doesn't look fine to me, but it needs to be looked at by active users of the library.
* Following up on that, I would like to look into potentially adding an Application model. Doing so seems like a more appropriate approach than what's been presented in the PR. Secret storage is still an open question, I do not want to force users to store private keys or anything like that in the database. Maybe we can do a mixed approach with secrets in the settings, apps in the db? I don't know. Needs a design doc.
* In general: Keeping the docs up to date, keeping the code clean and [the style in check](https://github.com/jleclanche/django-push-notifications/blob/master/CONTRIBUTING.md) and more than anything make sure that the stuff that gets merged actually works and is appropriately backwards-compatible (and if not, make a note of it)

I'd really like to do a new release of the library but that last point is especially tricky when it comes to that. I simply don't know the state of master right now, so I don't know if a release is appropriate.

**Comment by masnun** [comment]
Sorry for the late response. Yes, we're still using the library and I will be very happy to help. I got myself somewhat familiar with the code the last time. But it's been a while and I will have to take another look. I am going to do that and watch this repo in the mean time. 

I hope I can start contributing soon.

**Comment by Proper-Job** [comment]
@jleclanche I think it would be good to put the things you mentioned into a roadmap with milestones.  It'd be easier to prioritize that way and consolidate efforts. What do you think?

**Comment by jleclanche** [comment]
2.0 milestone lists everything that is on the high-priority todo:

https://github.com/jleclanche/django-push-notifications/milestone/5

Also, this:

https://github.com/jleclanche/django-push-notifications/issues?q=is%3Aopen+is%3Aissue+label%3A%22PR+Wanted%22

**Comment by jleclanche** [comment]
I also added an issue for replacing the HexIntegerField stuff. Ok guys, I'll take PRs / design docs for any of this stuff. I'll also give commit access to anyone who's committing to help maintain this lib at least a little.

**Comment by Proper-Job** [comment]
@jleclanche I'll take commit access. This is a good library and I'd like to see it stay alive.

**Comment by Antwan86** [comment]
I'd be up for giving a hand too (reviews / PRs / design suggestions / whatever)

**Comment by singleton11** [comment]
I'd change apns and gcm (and maybe wns) utilities to external dependencies to delegate responsibility (for support and testing) on them, and I'm just interested to this project

**Comment by jleclanche** [comment]
@Proper-Job @Antwan86 @singleton11 Thanks for your interest guys.

@Proper-Job @Antwan86  I've added you as a collaborator; please do file pull requests however unless you're committing something trivial. I also ask that you stick to the rules in [CONTRIBUTING.md](https://github.com/jleclanche/django-push-notifications/blob/master/CONTRIBUTING.md) (So the "All", "Git" and "Python" sections of the [HearthSim styleguide](https://hearthsim.info/styleguide/)).

@singleton11 Please go ahead and file pull requests for tasks which are free to take. Don't forget to make a note in the corresponding issue if you're taking it so that others don't. 

All: The [wiki](https://github.com/jleclanche/django-push-notifications/wiki) is all-access, if you want to help with documentation, recipes etc please feel free to use it.

**Comment by brad** [comment]
@jleclanche Have you considered handing the project over to [Jazzband](https://jazzband.co/)? I use several libraries that were suffering from lack of maintenance, but were very nicely cleaned up and revived by Jazzband.

**Comment by jleclanche** [comment]
Yes, I talked to them even, over a year ago and never heard back. I also got a really bad vibe from them to be honest.

Either way, concern isn't lack of organization (I can keep up with that), it's more the lack of contributions. Jazzband wouldn't fix that.

**Comment by sww314** [comment]
I can help as well. I use this library in a couple of projects right now.

**Comment by fladi** [comment]
I'm planning to package this library as a Debian package. As a result of this I'd be willing to help out with maintenance of this package. We (employer) are going to use both APNS and GCM/FCM in our current project.

**Comment by jleclanche** [comment]
Closing this, we got a bunch of collaborators now.
