### ISSUE TITLE
Process failed records?

### ISSUE THREAD

**Issue by saritasa** [jleclanche/django-push-notifications#206]
hi Guys,

```python
push_notifications.gcm.GCMError: {'multicast_id': 4623619281047227109, 'results': [{'error': 'MismatchSenderId'}], 'success': 0, 'canonical_ids': 0, 'failure': 1}
```

When bulk send_message() happens with failures - how to get a list of failed records?

**Comment by jamaalscarlett** [comment]
result["results"] contains the results from the send_message method, you could iterate through the list of results looking for the 'error'.  For reference, see the error handling in _gcm_send_json
