### ISSUE TITLE
Labels / tag for event registration

### ISSUE THREAD

**Issue by akatreyt** [jleclanche/django-push-notifications#209]
I'm wanting to use this for an event app I have, so I'm wanting to know if there is currently a way to add labels / tags when a user registers? My flow is when a user finds an event they click a I'm going button. This button will do a rest call and add the user + device, if not already added, and add the device id + event id as a tag. If the event creator updates the event, on the backend, it will find all devices with this tag and send a push out to the devices. 

Thanks

**Comment by jamaalscarlett** [comment]
You could fork the repo and add the event field the to device model.  Or you could create a new model in your app that has contains the event field and has a one to one relationship with each device created.

**Comment by akatreyt** [comment]
Thanks, i ended up going with creating my own model and using push notification app in that. 
I do have another question if anyone has time, this is what I'm doing to get all the devices to send a notification to:

This is my custom model
```
class RegisteredDeviceForEvent(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    device = generic.GenericForeignKey('content_type', 'object_id')
    event = models.ForeignKey(Event, blank=False)
    active = models.BooleanField(blank=False, default=True)
    created = models.DateTimeField(auto_now_add=True)
```


to get all registeredDevicesForEvent
```
all_device_ids_for_event = RegisteredDeviceForEvent.objects.filter(event=event, active=True)
```


when sending bulk do I have to send iOS and Android different? If so is this the best way to sort?
```
for item in all_device_ids_for_event:
                if type(item.device) is APNSDevice:
                    apns_list.append(item.device)
                elif type(item.device) is GCMDevice:
                    gcm_list.append(item.device)

if len(gcm_list) > 0:
    gcm_list.send_message(event_messaage)
if len(apns_list) > 0:
    apns_list.send_message(event_messaage)
```

or can I just do 


```
all_devices = []
for registeredDevice in all_device_ids_for_event:
    all_devices.append(registeredDevice.device)
all_devices.send_message(event_messaage)
```


Thanks for any direction.

**Comment by jamaalscarlett** [comment]
I like the last method.
