### ISSUE TITLE
send_message target active devices only

### ISSUE THREAD

**Issue by lcplusplus** [jleclanche/django-push-notifications#212]
send_message should not target only active devices?

ie:

change from:

```reg_ids = [rec.registration_id for rec in self]```

to:

```reg_ids = [rec.registration_id for rec in self if rec.active]```

I can specify active=True on the query for bulk messages, but not sure why this isn't implied in the code.

Should not active flag denote whether notifications will be sent?

Thanks for any clarification.

**Comment by lcplusplus** [comment]
I understand the device gets set false if it cannot send the notification to device , but I think this case still applies if user makes it explicit that they don't want notifications to be sent beforehand.

**Comment by jamaalscarlett** [comment]
Feel free to submit a pull request.
https://github.com/jleclanche/django-push-notifications/blob/master/CONTRIBUTING.md

**Comment by avichalp** [comment]
Hi, 

I think @lcplusplus has pointed out correctly. Notification should only be sent to active devices also it should be implied in the code. 

I have made the suggested changes. Here is the pull request
https://github.com/jleclanche/django-push-notifications/pull/221.

 Please review it.

Thanks, 
Avichalp

**Comment by jamaalscarlett** [comment]
Addressed in #221
