### ISSUE TITLE
GCM canonical IDs support

### ISSUE THREAD

**Issue by AlesDokshanin** [jleclanche/django-push-notifications#213]
GCM sends canonical registration IDs for devices to prevent duplicating messages on same device as seen [on the google docs] (https://developers.google.com/cloud-messaging/registration)
Will replacing current registration id with canonical one be implemented in this application?
If there is no problems in adding this feature I dont see, then I can try to implement it and send a pull request.

**Comment by jleclanche** [comment]
PRs welcome, yes. Feel free. Do take a look at the CONTRIBUTING.md document first:

https://github.com/jleclanche/django-push-notifications/blob/master/CONTRIBUTING.md

**Comment by jamaalscarlett** [comment]
This would be great.  I just ran into this issue during testing this weekend.

**Comment by tasn** [comment]
Hey, why was this issue closed? Was this fixed? Mind pointing me to the relevant commit?
