### ISSUE TITLE
MismatchSenderID on android

### ISSUE THREAD

**Issue by balkantechnologies** [jleclanche/django-push-notifications#220]
When trying to send a message (either individual or bulk) I get an error back:

```
Bulk: GCMError: {u'failure': 1, u'canonical_ids': 0, u'success': 0, u'multicast_id': 5441527391371826898, u'results': [{u'error': u'MismatchSenderId'}]}

Individual: GCMError: Error=MismatchSenderId
```

I have followed the instructions to setup everything and in my settings.py I have:

```python
PUSH_NOTIFICATIONS_SETTINGS = {
        "GCM_API_KEY": "my-api-key",
        "APNS_CERTIFICATE": "path/to/my/cert.pem",
}
```

From the Google developper docs I get the impression that also the sender ID has to be send and not only the API key.

Is this a bug or am I simply doing something very wrong?

**Comment by jleclanche** [comment]
Did you take a look at this?

https://stackoverflow.com/questions/11313342/why-do-i-get-mismatchsenderid-from-gcm-server-side

**Comment by balkantechnologies** [comment]
I found the problem: I shouldn't do programming before having my morning coffee...

In the client app I wrote the API key instead of the ClientID during the registration of the device and that caused the error. Changed that and everything works like a charm now.
