### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by danreeves** [jleclanche/django-push-notifications#232]
Latest version isn't on PyPI so I needed to reference the latest commit in my requirements.txt

**Comment by spacediver** [comment]
+1

**Comment by jleclanche** [comment]
I'll do a release and publish to pypi this week.

**Comment by jleclanche** [comment]
@jamaalscarlett Please verify if there's anything else that should land before release.

**Comment by jamaalscarlett** [comment]
If you could take a look at https://github.com/jleclanche/django-push-notifications/pull/218.  I'd like to get that in there if possible.

**Comment by jschneier** [comment]
:+1: please!

**Comment by jleclanche** [comment]
The latest version is on pypi now.
