### ISSUE TITLE
Proposal: model refactoring

### ISSUE THREAD

**Issue by koutoftimer** [jleclanche/django-push-notifications#234]
## Introduction

Currently only 2 fields are actually required for `GCMDevice` and `ANPSDevice` models, they are:
- `active` - which helps manage active devices 
- `registration_id` - required for identifying device which should receive push notification

What about other fields:
- `date_created` - required only in case if library user need track time, when specific device was added to internal database. For now, I have no use for this field.
- `user` - optional field, which links together user instance with it's devices. Actually some devices can be linked with groups or behave in very different way.
- `name` - very optional. Not every library user will use this option, because usually you only need to handle two distinct states: something have device or have not. Take care about naming devices is not main purpose of library for sending push notifications.

## Problems with extending current models

`Device` model have not all necessary information. As I mentioned above they are: `active` and `registration_id`. It is only abstract model and extending existing concrete models (GCMDevice or ANPSDevice) using `OneToOneField` will brings additional database overhead at least.

Why not make own concrete class with `Device` as base class?

- There are lot of tips and tricks about `registration_id` and `device_id` in model and DRF serializers and reimplementing their behavior is not fun.

## Proposal

Make two different base abstract models for each device type: 
- `BaseGCMDevice(registration_id: token, active: bool)`
- `BaseAPNSDevice(registration_id: token, active: boo)`

Base device model classed should be able to handle sending notifications, as they have all necessary information.

All optional fields append as mixin for concrete device model classes:
- `DeviceModelMixin(created: datetime, user: User, name: str)`
- `GCMDevice extends DeviceModelMixin, BaseGCMDevice`
- `APNSDevice extends DeviceModelMixin, BaseAPNSDevice`

Also concrete device models can implement any custom logic, that didn't match responsabilities of this library.

Serializers and views should behave in same way, e.g. `BaseGCMSerializer` handle model specific actions (validations, etc.) and concrete serializer (`GCMSerializer`) append logic specific for concrete device model.

With such approach we will receive library which do one thing - sends push notifications using minimal amount of required data, as well as allows extending very fast and easy.

**Comment by jleclanche** [comment]
Thanks for the thoughts. I'll let this stew for a bit and let others chime in.

**Comment by koutoftimer** [comment]
@jleclanche This approach should not break backward compatibility, but allow extending and using only parts that are really needed in concrete use cases.

**Comment by koutoftimer** [comment]
@jleclanche I think I have to implement this and look at people's feedback instead of waiting for joining discussion.

**Comment by jleclanche** [comment]
@koutoftimer Go for it.

**Comment by gkirkpatrick** [comment]
I'm curious what problem you're trying to solve by your proposal. It just seems more complicated for little gain. Is there an optimization you want? If any fields you don't want, you can ignore. Any overhead of a date-time field or a user field is really minimal. 

So far in my experience with Django, using sub-classes of model types or mix-ins is almost always more hassle than it's worth. Doing something like exporting the data to some analysis adds a step, and again, for what gain? Very little.

**Comment by koutoftimer** [comment]
@gkirkpatrick I have updated initial message.

> So far in my experience with Django, using sub-classes of model types or mix-ins is almost always more hassle than it's worth.

Have you ever create custom `User` model for any of your projects? Django use same approach itself.

> I'm curious what problem you're trying to solve by your proposal.

Make using library more handy by improving code readability and adding strict approaches about how things should be done in case if you want to extend `models`, `admin` or `api` modules.

**Comment by gkirkpatrick** [comment]
Thanks for the response - I can see the value of extending some of it.

I'd be curious to see how it works out. :)

**Comment by AndreasBackx** [comment]
I have [a fork](https://github.com/AndreasBackx/django-push-notifications/blob/master/push_notifications/models.py) for this specific purpose. It remains compatible with previous versions but adds the BareDevice and SimpleDevice models which can be APNS and GCM devices. There is also support for multiple APNS and GCM certificates/secrets which is something I needed.

I actually plan to rewrite this from scratch in a more OOP fashion and following the Python coding conventions. If someone is up for this kind of job, any help is appreciated. I'm currently working on some other stuff that I hope to open source in the future, but I can free some time for this.

**Comment by jleclanche** [comment]
@AndreasBackx I'd appreciate actual contributions. I mentioned several times I'm looking for comaintainers and nobody except Jamaal stepped up.

Regarding multiple APNS certs, I'd like to land the current PR but it's a huge change, still has some issues and I also see that the new APNS api is coming soon and will essentially remove the need for that FWIU.

As far as "OOP"ness and coding conventions go, if you mean in terms of separating apns/gcm from the django side I'd much rather see us move to a library like [pushjack](https://github.com/dgilland/pushjack) by @dgilland which was forked from this repo. If you mean in terms of switching to spaces, I got better things to do honestly...

**Comment by AndreasBackx** [comment]
@jleclanche when you mentioned you were looking for co-maintainers you were looking for people who could show that they were familiar with the library. Because I didn't contribute to the project, and I don't think making a fork is contributing, I didn't feel I was 'eligible'.

I am not familiar with pushjack, but I feel that approach is the way to go. I think we should split the messaging logic from the Django implementation. This provides other Python developers with a well established library that they can use however they please but still provide Django developers with an easy to use integration. We could make separate repositories, but I think it is wiser to go follow the approach of [python-social-auth](https://github.com/omab/python-social-auth) and provide implementations for multiple frameworks.

**Comment by jleclanche** [comment]
Well you're free to actually send PRs :) I admit they're kind of piling up but that's mostly because I have too little time myself. Bit of a catch 22, but I promise I'll make the effort at least.

I agree separating the protocol part is a good bet. I initially wrote django-push-notifications for a client so I didn't bother doubling the workload at the time.

I'm not really interested in providing flask compat myself (pushjack already does that), so I think django-push-notifications should stick to just providing the django interface and rely on a library to do the heavy lifting.

If people are interested I'd even be willing to create a gh org to host all this and try reduce the bus factor a bit.

**Comment by AndreasBackx** [comment]
I think we should decide on whether to make the 'base library' ourselves and add frameworks like Django and Flask (which can be added by anyone) or to perhaps move this to another repository like pushjack. In my opinion it is better to have the base library and framework integrations/implementations under the same library. Splitting the developers over 2 projects isn't the best of ideas in my book.

**Comment by koutoftimer** [comment]
@AndreasBackx, @jleclanche https://github.com/omab/python-social-auth previously was known as django social auth and if we decide to make something common for most frameworks, perhaps we should study their experience.

**Comment by AndreasBackx** [comment]
@koutoftimer yes indeed. Their transition from a only Django app to a more broad library is why I referred to them. It is the way we should go imo.

**Comment by jleclanche** [comment]
Who said anything about splitting the devs? It'd just be separate projects but the same devs.

I'm familiar with django-social-auth's transition. The main bonus is that we would likely *gain* devs who are interested in pushjack, push notifications on flask, etc. But again I'd need @dgilland to chime in here because I personally don't want to create a library virtually identical to it without good reason.

**Comment by AndreasBackx** [comment]
@jleclanche I feel that creating separate repositories is redundant. It would be better to incorporate everything into 1 repository. It makes it easier for new frameworks to be added and makes it easier for developers to join in.

My opinion is to either start a new library or build upon pushjack and add framework integrations.

**Comment by shigmas** [comment]
(jumping in late here)

@AndreasBackx it sounds like you just want to create a flask package with a dependency on pushjack. That seems better than turning this into a monolithic repository

**Comment by AndreasBackx** [comment]
@shigmas I want it to be available to any framework user. If there is no framework integration added yet, that they can also add it themselves. I'm no Flask developer so I wouldn't need a Flask integration. Limiting a push notifications library to solely Django and not even all of Python seems like a waste of potential.

**Comment by dgilland** [comment]
Pushjack author here.

I'm always open to contributions to [pushjack](https://github.com/dgilland/pushjack), but I've intentionally separated the Flask integration into a separate package mainly to keep `pushjack` agnostic towards web frameworks. I'd like to continue to keep the main `pushjack` package separate from any external integrations.

FWIW, an alternative to putting external integrations into `pushjack`, could be to create an integration package that depends on `pushjack` but implements the Flask, Django, and any other web framework integrations.

One example of this is [marshmallow](https://github.com/marshmallow-code/marshmallow) and [webargs](https://github.com/sloria/webargs). Internally, `webargs` uses `marshmallow` to provide request arg parsing/validation while `marshmallow` is agnostic towards a web framework.

**Comment by jleclanche** [comment]
@dgilland I'm 100% with you on pushjack's design. My proposal would be to move django-push-notifications to use pushjack internally and ideally I'd like us to collaborate on both projects.

Would you be open to a github org that would host the projects?

**Comment by AndreasBackx** [comment]
@dgilland Having 2 projects would be a good middle ground for both propositions.

@jleclanche Will we start from scratch? I'm all for starting from scratch as it isn't that big of a project for Django. I guess we will be needing a new name because it won't solely be for Django. Can we get an IRC channel going on Freenode so communication is a bit faster too?

**Comment by dgilland** [comment]
@jleclanche I'm not fundamentally opposed to an org that would include pushjack, but I'm reluctant to transfer ownership of the repo to an org where I don't personally or professionally know any of the other members. I'm all for collaboration between projects though.

**Comment by jleclanche** [comment]
Of course; same here - this isn't exactly urgent. Do you have skype or some such? (Try my github username if you do)

**Comment by AndreasBackx** [comment]
@dgilland I agree. Pull requests suffice. Can we get #pushjack or something else going on Freenode?

**Comment by dgilland** [comment]
I've created a Gitter room for pushjack: https://gitter.im/dgilland/pushjack

**Comment by dgilland** [comment]
Scratch the Gitter room. Use #pushjack on Freenode instead.

**Comment by jleclanche** [comment]
Closing

**Comment by MySecondLanguage** [comment]
> BareD

Can i know what version of this library containe BareDevice Class?
