### ISSUE TITLE
APNS Feedback Service Not Working

### ISSUE THREAD

**Issue by nikilster** [jleclanche/django-push-notifications#236]
I'm trying to use the Feedback Service to prune devices.  I tried selecting token in the admin panel that I know are inactive and did prune devices - all of the devices were still marked as active.

Questions:
1. How do you get this working in the admin panel?
2. How do you do this in code? (Could we get an explanation of how to do this)
3. We have both an enterprise cert and a app store cert - we need to only prune the device if it works for neither certificate - how do we do this?

@shigmas any thoughts?  Figured we'd ask the creator himself :)

Thanks in advance for the help!!

**Comment by shigmas** [comment]
It's been a long time since I wrote that...

How did you know they were inactive?  If you run prune either on the command line or in the web interface, it will only know that something is inactive if you've tried to send a message and it failed.  Is that not the behavior?

I didn't write anything to deal with two sets of certificates.  That wasn't supported when I implemented it, though I'd hope that it still works with multiple certificates.  But I'm not sure if your desired behavior matches everyone's expectations.

**Comment by nikilster** [comment]
Haha I'm impressed that you still remember how it works!

Yeah I tried sending to the token (the device that uses those tokens doesn't have the app anymore) and then tried running prune devices and nothing is returned.

I'm running it as ```python manage.py prune_devices``` right now

Do you have an example of how I could do this in code?  Thanks!!

**Comment by shigmas** [comment]
models.py has a function get_expired_tokens().  It's pretty simple - you'll see it call the APNS feedback service for any new id's that have failed since since you last tried sending a message to them (provided you haven't called the feedback service since then).

**Comment by nikilster** [comment]
Perfect thanks checking that out now! 

Also does work in the sandbox?

Also if you have a token for the prod push notifications and you try sending to that in the sandbox will that token show up in the expired tokens list?

**Comment by shigmas** [comment]
Obviously, the APNS servers have no idea what's in your database.  If you've tried sending notifications to devices on the sandbox and they've failed, then it will show up in the sandbox APNS feedback server.  If you've put them in your own database, then it'll mark them.  If they're not in the database yet, I don't think it will add them, but you should confirm that yourself.
