### ISSUE TITLE
push notificaton does not reach the device in orange Spanish provider

### ISSUE THREAD

**Issue by danihuge** [jleclanche/django-push-notifications#237]
I think they are using a proxy cache and push notifications are not reaching the devices... can it will be fixed??

I don't know, if the problem is in django or in android app.

regards,

**Comment by koutoftimer** [comment]
You can not send push notification directly to client, all work is done with help of intermediate services: GCM & APNS. None of them guarantee 100% message delivery.

**Comment by danihuge** [comment]
Yes, I know. I am using GCM but I have not any problem with others providers, the phones receive the notifications with any problem but with this one, the notifications are not reaching the devices. Perhaps some extra config in the app... I don't know...  
regards,

**Comment by koutoftimer** [comment]
Show minimal version of code that reproduce bug.

**Comment by jamaalscarlett** [comment]
@danihuge when you send the message, do you get a response from the gcm server?  If so then I agree with @koutoftimer, the issue is between the gcm server and your mobile app, not with this library.

**Comment by danihuge** [comment]
I need to do some tests and debug them. Great thanks for your responses. I am not sure there is a issue with library, I asked about similar issues with providers that they use proxy cache.
