### ISSUE TITLE
use raw_id_fields for user in admin change form

### ISSUE THREAD

**Issue by gpitfield** [jleclanche/django-push-notifications#240]
Currently, the admin change form uses the standard dropdown picker for the user in the Device change form. This becomes *very* problematic if there are more than a few thousand users in the database, and tends to break things entirely beyond that. Could the default setup for this be to user Django's raw_id_field instead? If there's a way to leave this as an option for the developer that would be great to, but otherwise I think it would be better to have this as the default.

**Comment by jleclanche** [comment]
I'm ok with making raw_id_fields the default since most instances will have enough users to justify it.

**Comment by jleclanche** [comment]
Can you submit a PR?

**Comment by jamaalscarlett** [comment]
Added - https://github.com/jleclanche/django-push-notifications/commit/9d24fc6d54f061828b52467a96606d0d0690aa97
