### ISSUE TITLE
Recommendations for pushing to a user

### ISSUE THREAD

**Issue by jschneier** [jleclanche/django-push-notifications#244]
Hi I have (what I assume) is a very common scenario where I'd like to communicate to my individual users (in response to some view logic) on 2 sides of a marketplace and I was wondering if there is a recommended way to do so? I've written the following 2 possible implementations of a method on my `User` object and would appreciate feedback / and submit that maybe we should add something like this to the docs.

```python
def notify(self, message, **kwargs):
    try:
        GCMDevice.objects.filter(user=self).send_message(message, **kwargs)
        APNSDevice.objects.filter(user=self).send_message(message, **kwargs)
    except NotificationError as e:
         logger.warn('NotifcationException: %s', e)
```
or
```python
def notify(self, message, **kwargs):
    devices = chain(self.gcmdevice_set.all(), self.apnsdevice_set.all())
    for device in filter(lambda d: d.is_active, devices):
        try:
            device.send_message(message, **kwargs)
        except NotificationError as e:
            logger.warn('NotificatioError: %s for %s(pk=%s)', e,
                        device.__class__.__name__, device.pk)
```
The fact that I need to `filter` on `is_active` is kind of unfortunate. How about adding `if not self.is_active: return` [here](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/models.py#L59) and in the [corresponding APNSDevice method](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/models.py#L90) as well?

**Comment by jamaalscarlett** [comment]
There is an active filter on the querysets, see lines 42 and 76 in models.py.  The same filter on the models seems fine to me, pull requests are welcomed.  FWIW I would favour your first method, I would think that the bulk message would perform better than iterating through a list of devices.

**Comment by jschneier** [comment]
@jamaalscarlett Yes. I saw the active filter on the querysets which is why I wrote the first method. The reason I like the second method is because it tells me which device in particular failed. Truth be told I don't really expect the user to have many (> 2) devices (or at least it's fairly uncommon I think).

Thanks. I'll submit a PR with my quick suggestion in a bit.
