### ISSUE TITLE
Does not supporting device id more than int range decimal representation. 

### ISSUE THREAD

**Issue by Mohammed-Aadil** [jleclanche/django-push-notifications#246]
Hey,
I had some issue regarding device id. I have three devices here to test. One of three device wasn't saving device data(device id, reg id etc..) and returning with exception "integer out of range for 'q' format code" .
So I debug this problem and I found the device id in long format I think which was the main issue for this library. Other devices having device id in integer format so It worked. 
I manually convert device id to hex like this:
device_id = hex(attr['device_id'])
if device_id[-1] == 'L':
        device_id = device_id[:-1]
this code take care of int and long integer and convert them to hex.
after conversion I am able to create model data successfully. 
I posting this as an issue... Hope you understand and solve it in future and many of us might having same issue.
Thanks.

**Comment by jamaalscarlett** [comment]
Should be fixed in the master branch.

**Comment by jamaalscarlett** [comment]
@Mohammed-Aadil have you tried the latest code from the head?

**Comment by Mohammed-Aadil** [comment]
Yeah I tried it, I used pip install django-push-notifications to install it, I guess it install latest version.

**Comment by jamaalscarlett** [comment]
@Mohammed-Aadil the command is:
sudo pip install git+https://github.com/jleclanche/django-push-notifications.git

**Comment by Mohammed-Aadil** [comment]
@jamaalscarlett  Thanks for your reply, Here i got thing working with above code that I wrote for conversion from device id to hex number. I know it is not standard but I dont want to mess with my working code.
