### ISSUE TITLE
store APNS certificate in env var

### ISSUE THREAD

**Issue by jschneier** [jleclanche/django-push-notifications#248]
Hi I usually deploy to Heroku and prefer to keep my entire certificate as an environment variable rather as a file. Is this a feature you'd be interested in accepting via pull-request?

**Comment by jleclanche** [comment]
I'm -1 on it, why can't the environment variable point to a file path instead? Any particular reason?

**Comment by piha** [comment]
I'm using this code in settings.py to load sertificate from ENV:
```python
# PUSH NOTIFICATIONS
apns_file_name = os.path.join(BASE_DIR, 'apns_sandbox.pem')
if os.environ.get('APNS_CERTIFICATE'):
    # create certificate file from ENV var
    from tempfile import NamedTemporaryFile
    import atexit
    apns_file = NamedTemporaryFile(delete=False)
    apns_file.write(bytes(os.environ.get('APNS_CERTIFICATE'), 'UTF-8'))
    apns_file.close()
    apns_file_name = apns_file.name

    def unlink_apns_file():
        os.unlink(apns_file_name)
    atexit.register(unlink_apns_file)  # remove certificate file on exit

PUSH_NOTIFICATIONS_SETTINGS = {
        'APNS_CERTIFICATE': apns_file_name
}
```

**Comment by jleclanche** [comment]
To be honest, this functionality belongs in settings.py and this is a good enough solution, so rejecting and closing.

**Comment by ninobaldo** [comment]
@jleclanche I'm think the issue here is how heroku deploy works. In order to deploy on heroku,  @jschneier must save the pem file on git repository. @jschneier , @jleclanche am I wrong?

@ilyatikhonov when used on heroku your solutions writes a temp file on each request?

**Comment by jschneier** [comment]
@ninobaldo no you are wrong. this solution worked for me. i stored the value env var and then wrote it to a temp file.

**Comment by ninobaldo** [comment]
@jschneier but does this not cause a file to be saved in every request? Heroku persists the pem?

**Comment by jschneier** [comment]
Only on application boot.

**Comment by ninobaldo** [comment]
Nice! Tks!

**Comment by ilyatikhonov** [comment]
Hi @ninobaldo, my solution creates a temp file only once per app instance during the initialization.

**Comment by Blutude** [comment]
When I use a temporary file like the solution provided by @ilyatikhonov, device.send_message() times out. I'm not sure how to debug this.
