### ISSUE TITLE
Tasklist 1.4.0

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/django-push-notifications#249]
I'd like to do a 1.4.0 release before christmas. Please comment here if there is anything specific you'd like to see in it. No big features please.

* [x] 1.9 compatibility (needs testing)
* [x] Review #245 for inclusion

**Comment by jleclanche** [comment]
@jamaalscarlett Can you check out django 1.9 compat?

**Comment by jamaalscarlett** [comment]
Sure thing.

**Comment by jamaalscarlett** [comment]
There is an error thrown during python 3.3 testing; however from the Django site: **Since Django 1.8, we’ve dropped support for Python 3.2 and 3.3.**  All other tests passed

**Comment by jamaalscarlett** [comment]
If we are dropping support for python 3.3, the tox.ini will need to be updated.

**Comment by jleclanche** [comment]
@jamaalscarlett Can you go ahead and land a python 3.3 drop?

**Comment by jamaalscarlett** [comment]
@jleclanche Will do.  Which versions of Python 3 are supported, the old tests ran against 3.2, 3.3, and 3.4.  The new tox tests only run against 3.3 and 3.4.  Setup.py says 3, 3.3, and 3.4 and the readme just states Python 3 compatable.  Since I'm updating all these files anyway, I'd like to have everything matching.

**Comment by jleclanche** [comment]
3.4 and 3.5.

**Comment by jamaalscarlett** [comment]
Landed.

**Comment by gio82** [comment]
I'd like to add two more feature if possible.
The first one is very important for me.

1. When sending bulk pushes APNS and GCM (as far as I know) stop the sending them at the first issue encountered. I already attempted to solve this see my pull request #156. I'm not alone with this issue: #242 

2. Multiple applications support #247

**Comment by jleclanche** [comment]
I'd like to land #156 but I can't vouch for the code, I want a second opinion on it before it lands.
#247 is in an awful state right now and cannot land.

**Comment by nnseva** [comment]
@jleclanche @gio82 #247 is fine, what do you mean? It contains a lot of changes, including new documentation, new test cases concerned to the new functionality.

**Comment by jleclanche** [comment]
@nnseva Please see guidelines in [CONTRIBUTING.md](https://github.com/jleclanche/django-push-notifications/blob/master/CONTRIBUTING.md). The commits are a mess right now.

In any case I don't want to delay 1.4 any further, so I'll try to do the release tonight.

**Comment by jleclanche** [comment]
1.4.0 is now on pypi, let me know if there's any issues with it.
