### ISSUE TITLE
SSLError SSL_CTX_use_PrivateKey_file

### ISSUE THREAD

**Issue by vincentleeuwen** [jleclanche/django-push-notifications#252]
Hi guys,

First of all, thanks for the library. I have some problems getting push notifications working (in sandbox mode), as I keep getting SSL error:

`[Errno 336265225] _ssl.c:351: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib`

First I figured there must be something wrong with the certificate. I tried a bunch of things (http://stackoverflow.com/questions/9380403/what-does-ssl-ctx-use-privatekey-file-problems-getting-password-error-indica) but still no success. Any ideas?

Thanks,

Vincent

**Comment by brad** [comment]
@vincentleeuwen Is your certificate password-protected? It should not be for use with this library. Take a look at https://github.com/jleclanche/django-push-notifications/issues/2 which is a similar issue and let us know if that helps

**Comment by vincentleeuwen** [comment]
@brad Thanks for the quick response! Got rid of the errors now!
