### ISSUE TITLE
'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by mrbaboon** [jleclanche/django-push-notifications#253]
Trying to pass a payload to a GCMDevice.  Throws exception at `_gcm_send_plain` on `values["data.%s" % (k)] = v.encode("utf-8")`

Looking at the JARs released by GCM, their payloads are strongly typed to `HashMap(String, String)`.

It seems that we need to convert payload keys & values to strings before trying to UTF8 them :)

Let me know if you'd like me to open a PR and get this fixed, or if it is something you'd rather have users handle themselves.

**Comment by jamaalscarlett** [comment]
PR are welcome.  Please read https://github.com/jleclanche/django-push-notifications/blob/master/CONTRIBUTING.md

**Comment by luanfonceca** [comment]
I am getting the same error, the only solution is to fix the code it self?
it is really wrong?

Thanks

**Comment by luanfonceca** [comment]
Hi folks, in my case this error was throwed when i put a integer in the `extra` argument of the `send_message` function. All the values inside that dict should be strings.

**Comment by jleclanche** [comment]
This should be handled at the user level. Thanks for the report though. Closing.
