### ISSUE TITLE
Feature request: Sending messages by topic

### ISSUE THREAD

**Issue by AnderUstarroz** [jleclanche/django-push-notifications#262]
Sending messages by topic is a "must have" feature and really easy to implement I believe. Just adding the param **to**:
```
	{
	  "to": "/topics/foo-bar",
	  "data": {
	    "message": "This is a GCM Topic Message!",
	   }
	}
```

**Comment by Proper-Job** [comment]
Let me be the first to say: "PRs are welcome".

**Comment by AnderUstarroz** [comment]
hahaha damn you @Proper-Job !!
I was about to do it and then I realized that there is no need to modify the code:

```
    from push_notifications.models import GCMDevice
    device = GCMDevice.objects.get(registration_id='YOUR_DEVICE_REGISTRATION_KEY')
    device.send_message("You've got mail", topic='/topics/my_topic')
```

Actually I am going to add this to the documentation
