### ISSUE TITLE
Updating a device via PUT with Django-Rest-Framework does not update the Device.user

### ISSUE THREAD

**Issue by salian** [jleclanche/django-push-notifications#268]
My workflow using Django-Rest-Framework is such: 
1) Register a device when my Android app is run for the first time. I am following a lazy registration pattern, so at this point, the user is not logged-in, and I have to use the `GCMDeviceViewSet` instead of the `GCMDeviceAuthorizedViewSet`.
2) When the user logs in at some future date, I wish to update the registered device with the user parameter. For this, I send a PUT request at the `/device/gcm/{registration_id}` detail endpoint.

Question: Does this workflow seem appropriate?

Issue: At this point, although the appropriate Authentication token is passed in the header (i.e. the user is logged-in) the `Device.user` is not updated. I think this is a bug, due to `perform_update()` not being implemented in `DeviceViewSetMixin()` in `rest_framework.py`.

My suggested fix is to override `perform_update()` in the `DeviceViewSetMixin` in `rest_framework.py`, similar to the existing `perform_create`

	def perform_update(self, serializer):
		if self.request.user.is_authenticated():
			serializer.save(user=self.request.user)
		return super(DeviceViewSetMixin, self).perform_update(serializer)

**Comment by jamaalscarlett** [comment]
@salian Why do you need to register the device as soon as the app is launched.  You really should only be registering the device after the user has registered and logged in.

**Comment by salian** [comment]
@jamaalscarlett Almost half of my app is usable without logging in. I want to retain the ability to send the occasional generic notification about fresh content to those users, aimed at getting them to use the app more.

**Comment by jamaalscarlett** [comment]
Fixed in #269
