### ISSUE TITLE
registration_id unique constraint fails on PUT (Update)

### ISSUE THREAD

**Issue by mr-const** [jleclanche/django-push-notifications#270]
We use GCMDeviceSerializer as nested serializer
```python
class DataSerializer(serializers.ModelSerializer):
    gcm_device = GCMDeviceSerializer(allow_null=True, required=False)
```
and it always fails validation when we try to update our Data object with message: `{"gcm_device":{"registration_id":["This field must be unique."]}}`

It seems that following code executes on both create and update calls:
```python
			# Work around an issue with validating the uniqueness of
			# registration ids of up to 4k
			'registration_id': {
				'validators': [
					UniqueValidator(queryset=GCMDevice.objects.all())
				]
			}
```

**Comment by jamaalscarlett** [comment]
This appears to be a known issue with writable nested serializers https://github.com/tomchristie/django-rest-framework/issues/2403
