### ISSUE TITLE
How to integrate push notification in my App

### ISSUE THREAD

**Issue by sunny777** [jleclanche/django-push-notifications#272]
I have a notification app through which admin create notification for user how can i integrate my notification app with push notification when i created a notification it should go via push notification to notify user boss you have a new message

**Comment by sunny777** [comment]
i am using python 2.7 and django 1.6

**Comment by jamaalscarlett** [comment]
https://github.com/jleclanche/django-push-notifications/blob/master/README.rst has documentation on how to send messages; however django 1.6 is not a supported version.

**Comment by sunny777** [comment]
i have created a rest api post call for push notification...
here is the code:-

class PushRegister(BaseHandler, APIView):
    authentication_classes = (rauthentication.SessionAuthentication,
                              rauthentication.TokenAuthentication, )
    permission_classes = (rpermissions.IsAuthenticated,)

    def post(self, request):
        status = 200
        user = request.user
        if not self.is_device():
            raise Http404('Member not found')

        DATA = request.data
        platform = DATA.get('platform')
        device_id = DATA.get('device_id')
        registration_id = DATA.get('registration_id')
        if platform and device_id:
            if platform == 'android':
                try:
                    device = GCMDevice.objects.get(user=user, device_id=device_id)
                except GCMDevice.DoesNotExist:
                    device = GCMDevice(name="android_%s" % (registration_id or device_id))
                except Exception, e:
                    device = None
            elif platform == 'ios':
                try:
                    device = APNSDevice.objects.get(user=user, device_id=device_id)
                except APNSDevice.DoesNotExist:
                    device = APNSDevice(name="ios_%s" % (registration_id or device_id))
                except Exception, e:
                    device = None
            else:
                device = None

            if device:
                device.device_id = device_id
                device.registration_id = registration_id
                device.user = user
                device.save()

                return rresponse.Response({
                    'status': 'success',
                    'data': {
                        'device_id_registered': 'yes',
                    },
                }, status=status)

        return rresponse.Response({
            'status': 'error',
            'data': {
                'device_id_registered': 'no',
            },
        }, status=status)


on post call request i am getting the 
platform
device_id
and registration_id 
but on response i am getting error device_id_registered': 'no'

**Comment by jamaalscarlett** [comment]
With this code snippet, the only way to return that error is if platform and device_id are both None.  The problem is not with this library, it is with the request you are processing.
