### ISSUE TITLE
iOS Notifications notifications not working on Apache2

### ISSUE THREAD

**Issue by bai14** [jleclanche/django-push-notifications#275]
Hi, and thanks for your work.

I installed your app on Apache2 webserver and everything worked fine until I set Debug = False. In this case iOS devices don't receive push notifications. I tried using both development and production certificates.

Can you help me?

Thanks.

**Comment by brad** [comment]
@bai14 It definitely needs to be a production certificate when DEBUG=False because it will send to the production APNS host:
https://github.com/jleclanche/django-push-notifications#settings-list
