### ISSUE TITLE
Send messange fails if there is no active devices

### ISSUE THREAD

**Issue by gitfred** [jleclanche/django-push-notifications#280]
Actual:
When there is no active devices (in queryset), push will try to proceed anyway: it will send empty "registration_ids" which causes 400 from googleapis.

Expected:
if registration_ids is empty, do not send.

**Comment by jamaalscarlett** [comment]
#282

**Comment by cosmith** [comment]
I have the same issue. Shouldn't the sending stop before? I fixed it by simply filtering only active devices before sending but I'm not sure if this is the expected way.
