### ISSUE TITLE
Question: Unable to get settings.USER_MODEL to work

### ISSUE THREAD

**Issue by charlie1kimo** [jleclanche/django-push-notifications#281]
Hi all,
I am using `django-push-notification 1.4.1`
I am new to this useful module, but I tried to configure my django app with this django-push-notifications app to work, and I would like to use a different foreign key model to the `user` property in the Device model. I looked through the documentation and figured that doing:
```
PUSH_NOTIFICATIONS_SETTINGS = {
    ...
    USER_MODEL = "myapp.myModel",
}
```
should work,but it's not for me.

I dig a little bit in the code and I figured that:
```
class Device(models.Model):
        name = models.CharField(max_length=255, verbose_name=_("Name"), blank=True, null=True)
        active = models.BooleanField(verbose_name=_("Is active"), default=True,
                help_text=_("Inactive devices will not be sent notifications"))
        user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
        ...
```

It seems to me that `user` is always set to `settings.AUTH_USER_MODEL`, but I would like to make it to use `settings.PUSH_NOTIFICATIONS.get('USER_MODEL')`. Is this a small bug? or is this how it should be? Am I missing something?

Thanks!

**Comment by jamaalscarlett** [comment]
The option to set the user model is not available in 1.4.1.  In order to use that feature you will need to use the master branch from this repo.
pip install git+https://github.com/jleclanche/django-push-notifications.git
