### ISSUE TITLE
Error 'ssl.SSLError: [SSL] PEM lib (_ssl.c:2580)' has come after following instructions

### ISSUE THREAD

**Issue by LeeKyungMoon** [jleclanche/django-push-notifications#283]

**Comment by LeeKyungMoon** [comment]
My python version is '2.7.10'. Could this be a problem?

**Comment by 1vank1n** [comment]
@LeeKyungMoon did you fix problem? I have same error...

**Comment by LeeKyungMoon** [comment]
@1vank1n  It was because *.pem file. I created this file in the wrong way. I think you need to check your way is right.

**Comment by limbera** [comment]
What was wrong with it @LeeKyungMoon ? I am getting the same error, what format does the certificate need to take?

**Comment by 1vank1n** [comment]
@limbera hi!

You need generate right certificate. 

On OSX = `openssl pkcs12 -in certificate.p12 -out certificate.pem -nodes -clcerts`

**Comment by limbera** [comment]
Thanks mate it's all working.

**Comment by LeeKyungMoon** [comment]
OK, glad to know that you solved this problem... I felt that somebody more may refer this issue again unfortunately. I followed this reference to make the right certificate 
http://www.apptuitions.com/generate-pem-file-for-push-notification/
I wish you guys solve it without much pain!
