### ISSUE TITLE
GCM collapse_key [question]

### ISSUE THREAD

**Issue by jandos** [jleclanche/django-push-notifications#285]
Hello,
I am using django-push-notifications with DRF.
Is it possible to somehow specify the collapse_key optional string for GCM?
Thanks.

**Comment by jamaalscarlett** [comment]
You can pass it as a kwarg to the send_message method.  See: https://github.com/jleclanche/django-push-notifications/blob/a6881bff007147863e45522f1a26573427fb6b77/tests/test_models.py#L55
