### ISSUE TITLE
Windows Phone support

### ISSUE THREAD

**Issue by SvetlanaM** [jleclanche/django-push-notifications#289]
Hi, do you consider Windows Phone push notification support? If no, I can create one and send pull request.

**Comment by jleclanche** [comment]
PRs welcome yes.

**Comment by gabrielpcosta18** [comment]
Are you already developing a support for Windows Phone?

**Comment by jleclanche** [comment]
Nobody is working on this to my knowledge, feel free.

**Comment by SvetlanaM** [comment]
I try to code a bit the next month.

**Comment by gabrielpcosta18** [comment]
Really cool. This support would be pretty nice.

**Comment by AdamBolfik** [comment]
Started working on WNS:

jleclanche/django-push-notifications#303

**Comment by jamaalscarlett** [comment]
See https://github.com/jleclanche/django-push-notifications/commit/f32d9d50d48802954a34ee9e48c930ba556fab54
