### ISSUE TITLE
APNSServerError: (8, 0) with Celery

### ISSUE THREAD

**Issue by OscarIHS** [jleclanche/django-push-notifications#295]
I'm having an strange issue when sending push notifications through APNS in async tasks with Celery.

Sometimes it raises APNSServerError: (8, 0). The '8' status means Invalid Token in APNS documentation, but the tokens seems to be valid. Actually, sending test message through admin panel works perfectly.

Furthermore, if I restart the celery service, everything goes fine, until it happens again. I've not updated the library or modify anything on the backend, and it was working perfectly some weeks ago.

Celery log:

```pytb
 File "/home/padelapp/backend_env/lib/python2.7/site-packages/push_notifications/models.py", line 72, in send_message
    return apns_send_bulk_message(registration_ids=reg_ids, alert=message, **kwargs)
  File "/home/padelapp/backend_env/lib/python2.7/site-packages/push_notifications/apns.py", line 224, in apns_send_bulk_message
    _apns_check_errors(socket)
  File "/home/padelapp/backend_env/lib/python2.7/site-packages/push_notifications/apns.py", line 95, in _apns_check_errors
    raise APNSServerError(status, identifier)
APNSServerError: (8, 0)
```

**Comment by chrisballinger** [comment]
I am getting this as well, all of a sudden.

**Comment by OscarIHS** [comment]
I finally found the issue. Some of the devices where registered with development certificates instead of production. When sending bulk messages, apple rejects the request if at least one of the registration ids are not from the same environment (Invalid Token).

The command prune_devices does not solve this. If the library finds an invalid token error it should deactivate the wrong registration id and try to send the notifications again.

Please read this article:
https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG3
