### ISSUE TITLE
Changing User on a Device

### ISSUE THREAD

**Issue by chozabu** [jleclanche/django-push-notifications#296]
Heyah - I see we can DELETE devices

I was wondering if the default behaviour for a device when POSTing should be

```
update_or_create(registration_id=registration_id, defaults={...})
```

updating the current user of a device, instead of rejecting the request due to a registration_id already being taken?

This way, if a user signs out of an app, then a different user signs in, the new user would get the push notifications?

**Comment by jamaalscarlett** [comment]
Logging in and creating a new user are separate events.  If I have an application, and the user attempts to login, that should be a update (PUT, PATCH) , not a create (POST).  Handling of those cases should occur in your mobile or webapp.

**Comment by chozabu** [comment]
I agree in principle - but consider this situation:

John is using an app, powered by django-push-notifications, and happily getting notifications
The device crashes, loses data, or otherwise logs john out, without removing his device information
John gives the device to Mary
Mary is now getting Johns notifications, even if she logs into the app - she no longer has Johns details but will still be receiving his notifications

Perhaps I am mis-understanding something - but this seems like a in-lib fixable situation?

**Comment by jamaalscarlett** [comment]
If the device info is still intact, the device model should be updated with the correct user.  I don't disagree with the scenario, I just think that it should be fixed in the app, not the library.  Just because a problem can be fixed by a library change, does not mean that that is the correct approach.

**Comment by chozabu** [comment]
but to implement that the app would either have to over-ride the current device registration routes, or create a new route that removes existing data from other users first (and use them instead of current routes)?

I mean - is there a situation where a user asks for push notifications to be sent to their device and it is better for them to be told `error: device id already registered` than to have the user with the device get their notifications?

I'll happily implement this internally if it really should not go in the lib, but it seems like a worse approach to me than just replacing an existing token if a duplicate is provided by another user?

**Comment by jamaalscarlett** [comment]
My vote would be to handle it at the app level. @jleclanche any thoughts.  I will admit that many of the DRF related issues that people have found do not affect me because I implemented DRF myself before it was added to this library.  So I am open to the change if there is a desire for it.

**Comment by chozabu** [comment]
Well - I'd be happy to implement at the app level, even skip implementing if I knew _why_ a device should be refused when it already exists - it feels like an anti-feature, but perhaps there is a good reason for this behaviour that I am missing?

**Comment by chozabu** [comment]
So, I've had a quick glance over the relevant area of code, and my exact proposed change should be:
1. before saving, search for a device with matching registration_id
2. if found, set serializer PK to device PK

I guess I will subclass the serializer and monkey-patch the view? Interested in doing it in-lib and submitting a PR, unless this is a change you guys don't want (or would happily implement in a couple of mins anyway)

**Comment by jleclanche** [comment]
@jamaalscarlett @chozabu If it's a very simple change at the DRF level I'm willing to take a (default false) boolean setting for it. If it's more than a couple of lines, it's to be solved at the app level.

**Comment by chozabu** [comment]
@jleclanche @jamaalscarlett 
I took a little longer than I intended to looking for a way to get the changes in a couple of lines and remain readable - ended up doing it in the app:  https://gist.github.com/chozabu/b0eae211db963fe56c0c55773e6a16c0  
but really, the change is just overriding the `create` method and adding ~5 lines, replacing

		serializer = self.get_serializer(data=request.data)

with

		serializer = None
		if settings.DPN_auto_update_matching_reg_id:
			instance = GCMDevice.objects.filter(registration_id=request.data['registration_id']).first()
			if instance:
				serializer = self.get_serializer(instance, data=request.data)
		if not serializer:
			serializer = self.get_serializer(data=request.data)

The viewsets now behave as I'd expect. Though, if seeing this functional bits of code makes it look like I am doing something stupid, I'd love to know!

**Comment by jamaalscarlett** [comment]
That looks acceptable to me.  Submit a PR.

**Comment by chozabu** [comment]
@jamaalscarlett I'm not 100% happy with the repetition of the two create methods, with the only change between them being the model the filter is applied to, but not too sure of a better way - we cant use `get_queryset` - since that is filtered to only the users own devices.

Having said that - I am very happy with the functional result, and willing write a commit similar to the gist above

**Comment by lukeburden** [comment]
It might make more sense to use the `active` flag for this purpose.

Registration IDs are basically unique for an app install and a device, as best we know. This means two users of a single device using a single installed app (this DOES happen, albeit infrequently) can attempt to register the same registration ID and hit a pointless validation error with your current approach.

If we used `unique_together` on `registration_id` and `user_id` and just deactivated previous rows with the matching `registration_id` previously exists for another user, it'd preserve the data and limit the sending of push notifications to all but the most recently active user for a device/app install combo.

Thoughts @jamaalscarlett @chozabu @jleclanche?

**Comment by jleclanche** [comment]
Fix landed, closing
