### ISSUE TITLE
Firebase Cloud Messaging (FCM) support?

### ISSUE THREAD

**Issue by ezheidtmann** [jleclanche/django-push-notifications#302]
Google's [docs](https://developers.google.com/cloud-messaging/) recommend building new apps with FCM rather than GCM:

> Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

I'm interested to hear others' opinions on this:
- Should I follow their advice? There doesn't seem to be a deprecation timeline for GCM.
- If FCM is the way to go, should I integrate by adapting `push_notifications` with something like an `FCMDevice`, or use a different library?

**Comment by jleclanche** [comment]
I'll take PRs for a new and separate backend. Once they properly shut down GCM, we can remove the gcm backend.

**Comment by schryer** [comment]
Perhaps you can use code from the newly released python-fcm package.

**Comment by BraisGabin** [comment]
This works for me as a quick workaround:
```py
PUSH_NOTIFICATIONS_SETTINGS = {
  "GCM_POST_URL": 'https://fcm.googleapis.com/fcm/send',
  # ...
}
```

> This ~~program~~ *snip* is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.

Use at your own risk

**Comment by schryer** [comment]
I needed for format the notification differently and add a few headers. 

```
post_data = dict(to=self.registration_id,
                         priority='high',
                         notification=dict(
                             title=title,
                             text=message,
                             click_action='OPEN_ACTIVITY_NOTIFICATIONS',
                             sound='default',
                            )
                         )
json_data = json.dumps(post_data)
headers = {
            'UserAgent': "FCM-Server",
            'Content-Type': 'application/json',
            'Authorization': 'key{}'.format(settings.PUSH_NOTIFICATIONS_SETTINGS['GCM_API_KEY'])}

response = requests.post(
            url=settings.PUSH_NOTIFICATIONS_SETTINGS['GCM_POST_URL'],
            data=json_data, headers=headers, verify=certifi.old_where())

response.raise_for_status()

return response.json
```

**Comment by andhieka** [comment]
I'm willing to help with a PR here, but I need some directions.

From a [Google FAQ](https://developers.google.com/cloud-messaging/faq):

> How is FCM server implementation different from GCM server implementation?
> 
> You won’t need to make any server-side protocol changes for the upgrade. The service protocol has not changed. However, note that all new server enhancements will be documented in FCM server documentation.

which means that there is actually nothing much to change here except the POST URL. I'm still reading up more on GCM and FCM docs but I'll appreciate tips on what needs to be done here.

**Comment by alexandreferreira** [comment]
Hi, I made a implementation off this topic, please take a look #336
