### ISSUE TITLE
The field device_id in Android must be a char field

### ISSUE THREAD

**Issue by BraisGabin** [jleclanche/django-push-notifications#307]
It's not a good idea to identify the device with a hardware value, what you want to identify is the installation. The best way to do that are an `uuid` or `InstanceId.getId()` (or the new `FirebaseInstanceId.getId()`). I'm not the only one that think so: [Best Practices for Unique Identifiers](https://developer.android.com/training/articles/user-data-ids.html).

The problem is that the model enforce us to store a hexadecimal value in `device_id` and this values aren't a hexadecimal values, they are strings.

A string filed can handle a hexadecimal value if you really want to store the `ANDROID_ID` or the `TelephonyManager.getDeviceId()` so this probably isn't a BC.

**Comment by jleclanche** [comment]
I think you're confused about the role of `device_id`. It's not meant to be used as a unique identifier, just informational.
