### ISSUE TITLE
GCMDevice fails on Postgres (Django 1.9+)

### ISSUE THREAD

**Issue by sgoll** [jleclanche/django-push-notifications#308]
When storing the 64-bit device ID for GCM devices, it has to be converted to a signed integer on Postgres backends.

However, the name of the Postgres backend was changed in Django 1.9: now `django.db.backends.postgresql` is the preferred way while `django.db.backends.postgresql_psycopg2 ` remains as fallback:

https://docs.djangoproject.com/en/1.9/ref/settings/#engine

Thus, the list of `signed_integer_engines` in fields.py has to be extended so that both names are supported:

https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/fields.py#L18

All in all, the current implementation of `HexIntegerField` seems rather delicate and susceptible to bugs. For instance, only the global `connection` object is used in `_using_signed_storage` as opposed to the connection the field is actually used with (`connection` argument). Then, fuzzy matching is performed in `db_type` but exact matching is required for `signed_integer_engines`. However, since this is out of scope for this issue, discussion should probably move to another ticket.

**Comment by jleclanche** [comment]
The fix was merged.
