### ISSUE TITLE
New push notification overrides older ones in Android.

### ISSUE THREAD

**Issue by GauravButola** [jleclanche/django-push-notifications#310]
I'm testing my app on Android right now and, if I send multiple push notifications to the device, only the last one shows up on the android notification tray.

From what I understand the message id has to be different for the new message to be registered as different than the previous ones, but I can't seem to figure out how to do it.

Thanks.

**Comment by jamaalscarlett** [comment]
Are you using a unique notification id for each message?

**Comment by GauravButola** [comment]
That's what I'm struggling to understand, @jamaalscarlett. I'm not really sure what argument to send the unique notification id in.

Thanks for your response.

**Comment by jamaalscarlett** [comment]
It is done when the notification is received from the gcm server in your android app.

**Comment by GauravButola** [comment]
Ah! I was under the impression that I'd have to send some unique ID in the GCM payload. SoI'll have to implement it in the app then.

Thanks for the help.
