### ISSUE TITLE
Use to register without associating it with a user

### ISSUE THREAD

**Issue by khantthulinn** [jleclanche/django-push-notifications#325]
Hello, 

I am still beginner in Django. I have used yours and if it is already authorized (I use JWT Token), I can register.

But, if user hasn't login yet, then I got 403 error. 

How shall I do so that user hasn't login and can register their token?

In my settings.py, 

```
    'DEFAULT_AUTHENTICATION_CLASSES':
        (
         'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
         ),

```

In my urls.py

```
from push_notifications.api.rest_framework import APNSDeviceViewSet
router = routers.DefaultRouter()
router.register(r'device/apns', APNSDeviceViewSet)

    url(r'^', include(router.urls)),

```

**Comment by jamaalscarlett** [comment]
@khantthulinn 
What about the REST_FRAMEWORK variable DEFAULT_PERMISSION_CLASSES, what is that set to?
If it is set to rest_framework.permissions.IsAuthenticated, all requests processed by django rest framework need to be authenticated.  You can leave DEFAULT_PERMISSION_CLASSES empty and that should allow you to access that endpoint when the user is unauthorized.

**Comment by khantthulinn** [comment]
Yes. I have done that now but I still got same error. How shall I do?

`  "detail": "CSRF Failed: CSRF token missing or incorrect."
`

**Comment by khantthulinn** [comment]
I got it now. It is because of this in default.  That's why it is asking csrf token. When I do for my own apiview, it doesn't ask about csrf though. 

`         'rest_framework.authentication.SessionAuthentication',
`
