### ISSUE TITLE
Register token as no user and later update user

### ISSUE THREAD

**Issue by khantthulinn** [jleclanche/django-push-notifications#326]
I am using APNSDeviceViewSet so that I can register without login (I use JWT token). With that one, I can also register as authenticated user.

There is one issue for my application. Login to my app is optional. As a result, I register as non-authenticated user first. Later, after user login to app, I register again as authenticated user. But, I notice that if same token is used again, it is not allowed to update again. 

How shall I do?

**Comment by jamaalscarlett** [comment]
@khantthulinn what error are you receiving?

**Comment by khantthulinn** [comment]
Since I am running from ios app, I got 

Request failed: bad request (400)

When I use postman, I got

{
  "registration_id": [
    "APNS device with this Registration ID already exists."
  ]
}

**Comment by jamaalscarlett** [comment]
@khantthulinn what is the rest call you are making?  That looks like you are doing a post, if you are trying to update an existing record, your request method should be a PUT or a PATCH

**Comment by khantthulinn** [comment]
Amm I got this when I do PUT or PATCH.

  "detail": "Method \"PUT\" not allowed."
  "detail": "Method \"PATCH\" not allowed."

**Comment by jamaalscarlett** [comment]
a put or patch cannot be done on your gcm_device endpoint.  You need to specify an instance: 
so this will fail:
curl -X PATCH http://your_ip/gcm_devices/ -d '{"name": "new name"}'
but this should work:
curl -X PATCH https://your_ip/gcm_devices/reg_id/ -d '{"name": "new name"}'

**Comment by khantthulinn** [comment]
hi  I am using apns. what is reg_id?

**Comment by khantthulinn** [comment]
Argh...I got it now. Thanks you for your help. I am using apns though. I will put my token like that.
