### ISSUE TITLE
Tastypie lacks input validation

### ISSUE THREAD

**Issue by jaddison** [jleclanche/django-push-notifications#338]
If tastypie is being abandoned, then please ignore this issue. If not, read on.

I can use `curl` to throw the same device/registration data at the tastypie endpoint and it will happily return `201 Created`. Unlike the django-rest-framework API resources/viewsets, tastypie doesn't perform any validation.

**Comment by jleclanche** [comment]
Tastypie is abandoned yeah. It'll be removed before next release I think.
