### ISSUE TITLE
FCM support

### ISSUE THREAD

**Issue by danieltigse** [jleclanche/django-push-notifications#349]
I just installed the last version but I can't send a message via FCM. I checked the files inside side-packages/push_notifications/gcm.py and there is nothing about GCM. Help please.

**Comment by jamaalscarlett** [comment]
@danieltigse do you mean nothing about FCM?  It may not be in a released version.  Are you deploying from pypi, or building from source?

**Comment by danieltigse** [comment]
Ohh I thought It was in the release version. Are you planning to release a new version? Meanwhile do you recommend me to build from source?

**Comment by jamaalscarlett** [comment]
If you specifically want FCM, I would recommend waiting.  See https://github.com/jleclanche/django-push-notifications/issues/343

**Comment by jleclanche** [comment]
Merging into #343
