### ISSUE TITLE
Migration 0002_auto_20160106_0850 fails on MySQL/InnoDB with UTF8, key length too long

### ISSUE THREAD

**Issue by bctiemann** [jleclanche/django-push-notifications#353]
Running the migration I get:

django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

My database is set to use InnoDB with UTF8mb4 encoding. I can manually perform the change made by this migration by setting the field to latin1, but with my default UTF8 the migration tries to make the field too long to save.

**Comment by jleclanche** [comment]
This is #298.
