### ISSUE TITLE
Show sent registration ids in GCMError

### ISSUE THREAD

**Issue by tasn** [jleclanche/django-push-notifications#354]
Hey,

At the moment when GCMError is created, it's created with the server's response. The problem with this approach is that the server doesn't show the registration ids used. This in turn makes it rather annoying to trace back issues and trying to understand why a certain message was sent (both in bulk mode and not). 

My actual scenario: I'm sending a bulk message to a few registration_ids and I have not even the slightest idea which registration id caused what error. One of the ids is causing "InvalidParameters" for some reason, which doesn't make sense to me (because the rest work) so I'd like to investigate more, but the lack of such information makes it very annoying for me to do so (I have to patch my code).

Please consider this.

Thanks,
Tom.

**Comment by jamaalscarlett** [comment]
@jleclanche what do you think?

**Comment by tasn** [comment]
ping

**Comment by jleclanche** [comment]
Sorry for the delay. Yes, it sounds like we need to make the reg IDs available somehow. I would subclass the exception and add the reg ids as an attribute of it.

**Comment by tasn** [comment]
Cool. Looking forward. I never managed to solve my InvalidParameters issue (didn't have time to deal with it), ended up just ignoring this error code (bad!). I hope that when this change lands I'll be able to properly trace the offending regid.

Thanks.

**Comment by jleclanche** [comment]
I'm not going to be working on this myself, this is open for PRs tho

**Comment by jamaalscarlett** [comment]
https://github.com/jleclanche/django-push-notifications/blob/fd782a03d17e33eb873f5c5640e57baea45e4003/push_notifications/gcm.py#L86
Take a look at that code.  Even when there is an error, the response should contain the offending registration ids and the error type
See this from the gcm developer page:
https://developers.google.com/cloud-messaging/http
{ "multicast_id": 216,
  "success": 3,
  "failure": 3,
  "canonical_ids": 1,
  "results": [
    { "message_id": "1:0408" },
    { "error": "Unavailable" },
    { "error": "InvalidRegistration" },
    { "message_id": "1:1516" },
    { "message_id": "1:2342", "registration_id": "32" },
    { "error": "NotRegistered"}
  ]
}
the index in the results list should map to the list of ids you pass to the send method.

**Comment by tasn** [comment]
@jamaalscarlett, it wasn't clear in my initial report, so let me clarify.

When you send more than "max reciptients", the sending is split into chunks, see: https://github.com/jleclanche/django-push-notifications/blob/fd782a03d17e33eb873f5c5640e57baea45e4003/push_notifications/gcm.py#L206
This makes the index useless because you can't know if you are in chunk 1, 2 or 3.

See the problem?

**Comment by jamaalscarlett** [comment]
@tasn got it, thanks for the clarification.

**Comment by jamaalscarlett** [comment]
@tasn can you try the master branch?
