### ISSUE TITLE
Application Support 1.5 Proposal

### ISSUE THREAD

**Issue by matthewh** [jleclanche/django-push-notifications#366]
This is an intermediate step before implementing full in database support for multiple applications. 

* Move drf and tastypie integrations into push_notifications.contrib. Add deprecated warnings at their current location for backwards compatibility.
* Add support for configuration adapters.
    * Add a LegacySettingsAdapter that supports the existing format. (this will be default)
    * Add a AppIDSettingsAdapter that address applications by application_id for all platforms. (this will be default)
* Add support for application_id based on the current PR but skip any "other" features at this time.

This proposal suggests an alternate settings format as well as formally supporting additional contributed features via a push_notifications.contrib module. The drf and tastypie integrations would be moved here (with links maintained in their old locations for backwards compatibility). 

Additionally, the registry module that provides mobile clients to register tokens and other backend services to send push notifications through an API would be under push_notifications.contrib. (more to come on registry in another proposal).

```
PUSH_NOTIFICATIONS_SETTINGS = {
    # defines where to load application configuration from,
    # default will be the old file format from settings.py (LegacySettingsAdapter).
    "CONFIG_ADAPTER": "push_notifications.adapters.AppIDSettingsAdapter"

    # new array of all applications in the push_notifications
    "APPLICATIONS": [
        {
            # required - indicates what fields are needed to get api key or details: FCM, GCM, IOS, WNS
            "PLATFORM": "FCM",

            # required, how to address messages to this client from code
            "APPLICATION_ID": "my_fcm_app" 

            # optional, will be "default", allows for addressing devices across platform boundaries.
            # For instance, I have an android and ios version of my application
            # and I'd like to notify all users of a special announcement.
            "APPLICATION_GROUP": "my_application",

            # optional. if set, integrates with contrib.registry to allow mobile
            # applications to add keys (in situations where user authentication is not desired)
            "APPLICATION_SECRET": "d0910e22bd008b8ef603f5432d1e7020568ca0e9"

            # fcm setting
            "API_KEY": "[your api key]",
        },
        {
            "PLATFORM": "IOS",  # required - indicates what fields are needed to get api key or details: FCM, GCM, IOS, WNS

            # required, how to address messages to this client from code
            "APPLICATION_ID": "my_ios_app" 

            # optional, will be "default", allows for addressing devices across platform boundaries.
            # For instance, I have an android and ios version of my application
            # and I'd like to notify all users of a special announcement.
            "APPLICATION_GROUP": "my_application",

            # optional. if set, integrates with contrib.registry to allow mobile
            # applications to add keys (in situations where user authentication is not desired)
            "APPLICATION_SECRET": "d0910e22bd008b8ef603f5432d1e7020568ca0e9"

            # ios setting
            "APNS_CERTIFICATE": "/path/to/your/certificate.pem",
        },
        {
            "PLATFORM": "WNS",  # required - indicates what fields are needed to get api key or details: FCM, GCM, IOS, WNS

            # required, how to address messages to this client from code
            "APPLICATION_ID": "my_wns_app" 

            # optional, will be "default", allows for addressing devices across platform boundaries.
            # For instance, I have an android and ios version of my application
            # and I'd like to notify all users of a special announcement.
            "APPLICATION_GROUP": "my_application",

            # optional. if set, integrates with contrib.registry to allow mobile
            # applications to add keys (in situations where user authentication is not desired)
            "APPLICATION_SECRET": "d0910e22bd008b8ef603f5432d1e7020568ca0e9"

            # wns settings
            "WNS_PACKAGE_SECURITY_ID": "[your package security id, e.g: 'ms-app://e-3-4-6234...']",
            "WNS_SECRET_KEY": "[your app secret key, e.g.: 'KDiejnLKDUWodsjmewuSZkk']",
        }
    ]
}
```

**Comment by jleclanche** [comment]
> Move drf and tastypie integrations into push_notifications.contrib.

Not opposed to it but seems unnecessary, and unrelated to this new adapter system. Also, tastypie is going away soon as someone PR's a removal for it.

> Add support for application_id based on the current PR but skip any "other" features at this time.

Shall we skip application groups as well for this release then?

Rest looks good, +1

**Comment by matthewh** [comment]
I had a couple ideas for other components that would fit well into a contrib module but if tastypie is going away I'll raise the question again when I have something concrete.

I didn't want to skip groups because I need it. However if you tell me you'll approve a separate PR for application groups then I'm fine skipping that for now.

**Comment by jleclanche** [comment]
I'm +1 on application groups, but I'd like to do a release with as little "new" stuff as possible. At this point I just want to land this big thing and release 1.5 soon as you tell me it's good to go.

> Also I was waffling on wether to make the applications collection a list or dict. As a dict it makes the application_id lookup constant.

I don't care either way tbh.

**Comment by matthewh** [comment]
I have a few other tasks to address this morning but I should be able to get a PR ready this evening (EST).

**Comment by jleclanche** [comment]
No rush, I won't be able to get to this today, but others should review it too anyway.

**Comment by jamaalscarlett** [comment]
This looks great.  I like the idea of application groups too, but I understand if you want a minimal first cut.

**Comment by matthewh** [comment]
I just wanted to follow up and say this week didn't go as expected. My kids were sick and then I got sick. Everyone is feeling better now so I'm working on this again.

**Comment by jleclanche** [comment]
We landed this.
