### ISSUE TITLE
Still getting "APNS device with this Registration ID already exists." or {"detail": "Not found."}

### ISSUE THREAD

**Issue by andreyshipilov** [jleclanche/django-push-notifications#374]
I have this one in settings: `UPDATE_ON_DUPLICATE_REG_ID = True`

Logging in as a different User, but want to register the same device.

Receiving this when POSTing to ../apns/
```
{
  "registration_id": [
    "APNS device with this Registration ID already exists."
  ]
}
```
Receiving this when PATCHing to ../apns/apns/{registration_id}/
```
{
  "detail": "Not found."
}
```
Am I missing something or doing something wrong?

Thanks ahead.

**Comment by andreyshipilov** [comment]
For some reason `pip install django-push-notifications` did not install the latest version. I mean it installs version 1.4.1, but there's nothing about `UPDATE_ON_DUPLICATE_REG_ID` setting there.

**Comment by jleclanche** [comment]
Yes, see #373. I'll be doing a 1.5.0 release as soon as the last couple of blockers land, hopefully within the next few weeks.

**Comment by andreyshipilov** [comment]
Ah, sweet. I'm gonna be deploying the app just with latest master branch for now.
