### ISSUE TITLE
GCM device doesn't have cloud_message_type field

### ISSUE THREAD

**Issue by viinhpham** [jleclanche/django-push-notifications#379]
I am using django-push-notification verion 1.4.1 and getting this error:

django.core.exceptions.FieldError: Cannot resolve keyword 'cloud_message_type' into field. Choices are: active, date_created, device_id, id, name, registration_id, user, user_id

I checked to see that GCM device doesn't have cloud_message_type field but it does in master branch.
How can I resolve this?

**Comment by jamaalscarlett** [comment]
You can pip install from the master branch, which is the unreleased stable branch.
```pip install git+https://github.com/jleclanche/django-push-notifications.git```
The readme for the 1.4.1 is here:
https://github.com/jleclanche/django-push-notifications/tree/1.4.1

**Comment by viinhpham** [comment]
Okay thank you for your help @jamaalscarlett
