### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by matthewh** [jleclanche/django-push-notifications#381]
@jleclanche What else needs to be completed to release 1.5? I believe the open tickets for the 1.5 milestone are all handled now.

I'd like to get that wrapped up and start on a 2.0 where we remove replace the HexIntegerField and relax the registration_id constraint for APNS. I'm still running a fork to address both of those.

**Comment by jleclanche** [comment]
If you can confidently say master works fine, I'll make it a release.

**Comment by matthewh** [comment]
My confidence would increase if we hear back from @khantthulinn or @shipilov. They both expressed interest in the new configuration.

**Comment by matthewh** [comment]
In the meantime, how do you want to handle the HexIntegerField and registration_id constraint for APNS? I'd like to get started on that.

**Comment by andreyshipilov** [comment]
Can confirm. Multiple app settings works fine over here.

**Comment by jleclanche** [comment]
Django Push Notifications 1.5.0 has been released 🎉 🎉 🎉 . Special thanks to @jamaalscarlett, @matthewh and @kit-cat for carrying this one :) 

Things should be a lot simpler now. With this release out, we can now be a bit more lenient with backwards incompatibility and move forward on [all this stuff](https://github.com/jleclanche/django-push-notifications/milestone/5). :)

**Comment by kit-cat** [comment]
@jleclanche yay ! Congratulations 🎉
