### ISSUE TITLE
Wrong POST url for FCM as an result of get_post_url

### ISSUE THREAD

**Issue by sylwekb** [jleclanche/django-push-notifications#383]
I cannot send any messages via FCM. I fixed it by putting hardcoded FCM POST url in this line:
https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/gcm.py#L71

**Comment by matthewh** [comment]
Thank you for submitting a bug report. The issue has been identified and will be fixed shortly.

**Comment by matthewh** [comment]
@sylwekb The issue should be addressed now. If I may suggest, try out the new configuration explained in https://github.com/jleclanche/django-push-notifications/wiki/Multiple-Application-Support.
