### ISSUE TITLE
Unable to import .apns.apns_fetch_inactive_ids

### ISSUE THREAD

**Issue by facconi** [jleclanche/django-push-notifications#389]
Hi. I'm using master version of django-push-notifications.
When I run the manage command prune_devices, I get the following error:

```
(env) $ ./manage.py prune_devices
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
    (snip)
    from .apns import apns_fetch_inactive_ids
ImportError: cannot import name apns_fetch_inactive_ids
```

apns.py does not contain apns_fetch_inactive_ids!

Searching in the repository code, the apns_fetch_inactive_ids function is not found anywhere outside the manage command:

<img width="707" alt="shot" src="https://cloud.githubusercontent.com/assets/292414/25269820/91ced488-267e-11e7-9201-65297f4009e2.png">

Hope this issue helps!

**Comment by matthewh** [comment]
@facconi The management command prune_devices was removed in the 1.5 release. Devices are now pruned automatically by pyapns2. If you check the master branch you'll notice there are no longer any management commands in this project. If you are running from source, please confirm that those files are no longer present locally and double check you don't have any stale pyc files floating around - they are a common cause of weirdness like this.

**Comment by facconi** [comment]
I'll check, thank you for the answer.
