### ISSUE TITLE
Firebase notifications are not displayed in the console.firebase.google.com

### ISSUE THREAD

**Issue by Xepe** [jleclanche/django-push-notifications#390]
Hello, 

I am working with firebase and I did all the configurations, the messages is sent and the phone is receiving  the message correctly, but in the notifications section in the firebase page the messages are not displayed. 

I am just using: 

`fcm_device.send_message("This is a message")`

Regards

**Comment by jamaalscarlett** [comment]
@Xepe  Are you sure that the firebase console is suppose to display all notifications sent?  My understanding is that it displays notifications sent using the Firebase console gui.

**Comment by Xepe** [comment]
Thanks for answering, you are right.

I was looking some information about this, I think that the only way to see if the notifications were sent is using the events in the analytics section in firebase. 

In my scenario I need to keep a tracking of the messages sent for specific devices, I thought that firebase was handling this information as in the console gui but it does not.

Regards.
