### ISSUE TITLE
SSL: TLSV1_ALERT_INTERNAL_ERROR when connecting to APNS

### ISSUE THREAD

**Issue by Tamarabyte** [jleclanche/django-push-notifications#399]
My servers APNS notifications recently stopped working and after debugging I found that the SSL python library is throwing the following error when opening a socket:

      File "/home/tam/repos/rest/api/tasks/notification_tasks.py", line 17, in apns_socket
    self._apns_socket = apns.open_apns_socket()
      File "/home/tam/repos/rest/api/utilities/apns.py", line 64, in open_apns_socket
    return _apns_create_socket((settings.APNS_HOST, settings.APNS_PORT))
      File "/home/tam/repos/rest/api/utilities/apns.py", line 49, in _apns_create_socket
    sock.connect(address_tuple)
      File "/usr/lib64/python3.5/ssl.py", line 1014, in connect
        self._real_connect(addr, False)
      File "/usr/lib64/python3.5/ssl.py", line 1005, in _real_connect
        self.do_handshake()
      File "/usr/lib64/python3.5/ssl.py", line 983, in do_handshake
        self._sslobj.do_handshake()
      File "/usr/lib64/python3.5/ssl.py", line 628, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)

Nothing has changed on the server codewise. I've checked APNS certificates (they haven't expired), and our SSL certificate (also not expired). I'm unsure what else could be causing this error at this point.

Here are the relavent lines of code from apns.py:

    def open_apns_socket():
        return _apns_create_socket((settings.APNS_HOST, settings.APNS_PORT))

    def _apns_create_socket(address_tuple, is_dev=False):
        certfile = settings.APS_CERTIFICATE
        if not certfile:
            raise ImproperlyConfigured('You need to set settings.APNS_CERTIFICATE')
    
        try:
            with open(certfile, "r") as f:
                f.read()
        except Exception as e:
            raise ImproperlyConfigured("The APNS certificate file at %r is not readable: %s" % (certfile, e))
    
        ca_certs = settings.APNS_CA_CERTIFICATES
    
        sock = socket.socket()
        sock = ssl.wrap_socket(sock, ssl_version=ssl.PROTOCOL_TLSv1, certfile=certfile, ca_certs=ca_certs)
        sock.connect(address_tuple)
    
        return sock

APNS_HOST = "gateway.push.apple.com"
  
APNS_PORT = 2195

**Comment by chrisballinger** [comment]
I've seen this before. Even though it's not expired, try regenerating your cert anyway.

**Comment by Tamarabyte** [comment]
Hey Chris! Thanks for insight! my APNS cert or SSL one?

**Comment by chrisballinger** [comment]
APNS cert

**Comment by Tamarabyte** [comment]
Worked perfectly. Thanks a bunch for deciphering that cryptic error.
