### ISSUE TITLE
UPDATE_ON_DUPLICATE_REG_ID not taking effect

### ISSUE THREAD

**Issue by farice** [jleclanche/django-push-notifications#402]
I've set this value to `True` in my `Project/settings.py` file. However, I still get a validation error when a registration ID associated with another account is POSTed to `/device/apns/`.  If I manually delete the conflicting reg id instance from shell and send the same POST it works fine, so it's clear that the reg id conflict is the issue. Hence, `UPDATE_ON_DUPLICATE_REG_ID=True` seems to be the fix but has no effect (even after restarting apache etc). 

DRF=3.6.2
Django=1.11.1

Any ideas?

**Comment by jamaalscarlett** [comment]
@farice Are you setting UPDATE_ON_DUPLICATE_REG_ID to True in the PUSH_NOTIFICATIONS_SETTINGS dict in settings.py?  If not, that would explain why the setting is being ignored.

**Comment by jamaalscarlett** [comment]
@farice bump

**Comment by farice** [comment]
You are correct! Sorry for the late response. @jamaalscarlett
