### ISSUE TITLE
ImproperlyConfigured : push_notifications.conf.AppConfig requires the application_id be specified at all times.

### ISSUE THREAD

**Issue by BuissonReda** [jleclanche/django-push-notifications#414]
Hello, when trying to send a push notification to an APNS device, I get this error. I tried to create a push notification settings file following this guide :
https://github.com/jleclanche/django-push-notifications/wiki/Multiple-Application-Support
But it says : 
"Applications must be added to the PUSH_NOTIFICATIONS_SETTINGS["APPLICATIONS"] dictionary.
The dictionary key is the APPLICATION_ID"
However we are trying to implement push notifications on a hybrid application (with Ionic 3) and we cannot use the application_id as a key since we have the same application_id for iOS and Android (and any other additional platform we would use). Can we still make it work with a unique application_id ?

Django push notifications : 1.5.0
Django Version : 1.11.2
Python Version : 3.5.0

**Comment by matthewh** [comment]
The application id is a string you make up. You can use different values and still talk to the same "app".

I usually append the platform to my app names: myapp-fcm, myapp-ios, etc. 

I hope that helps.

**Comment by BuissonReda** [comment]
I know that the application id is a string that I make up, but as I said it is unique because of the nature of my app (hybrid). I choose it once in a file, config.xml, and it is used in each platform (ios, android, windows phone...)

I would like to append my platform to my application id, but for example, for ios, I would have to re-create an application on the app store, create new certificates, etc. This is something I wanna avoid.

**Comment by matthewh** [comment]
You do not need to recreate your application when you change the Django Push Notification <application_id>.

The application id used by Django Push Notifications in no way bound or tied to the various app store bundle/app identifiers. It is just a label used to group a configuration and a set of devices to a specific PUSH API. The API_KEY (fcm/gcm) or CERTIFICATE (APNS) values are the important pieces that tell Django Push Notifications how to talk to your app.

It is common in iOS to define multiple entries under applications that use the same CERTIFICATE. For instance, here is my configuration with various names changed. One iOS app is split into 3 to support voip, development, and standard push notifications. Note that my <application_id> has no relation to my iOS app/bundle id.

```
"my_ios_app-voip": {
      "PLATFORM": "APNS",
      "CERTIFICATE": "/path/to/your/certificate.pem",
     "TOPIC": "com.example.someappname.voip"
},
"my_ios_app-silent": {
      "PLATFORM": "APNS",
      "CERTIFICATE": "/path/to/your/certificate.pem",
     "TOPIC": "com.example.someappname.shh"
},
"my_ios_app-dev": {
      "PLATFORM": "APNS",
      "CERTIFICATE": "/path/to/your/certificate.pem",
      "APNS_USE_SANDBOX": True
}
```

**Comment by BuissonReda** [comment]
Ok, this is clear now. Thanks for your fast answers!

**Comment by matthewh** [comment]
Happy to help. Good luck with your project.

**Comment by lalit-lintel** [comment]
Hi Issue with GCM device, not saving application_id.

**Comment by afzoun** [comment]
> You do not need to recreate your application when you change the Django Push Notification <application_id>.
> 
> The application id used by Django Push Notifications in no way bound or tied to the various app store bundle/app identifiers. It is just a label used to group a configuration and a set of devices to a specific PUSH API. The API_KEY (fcm/gcm) or CERTIFICATE (APNS) values are the important pieces that tell Django Push Notifications how to talk to your app.
> 
> It is common in iOS to define multiple entries under applications that use the same CERTIFICATE. For instance, here is my configuration with various names changed. One iOS app has 3 entries to support voip, development, and standard push notifications. Note that my <application_id> has no relation to my iOS app/bundle id.
> 
> ```
> "my_ios_app-voip": {
>       "PLATFORM": "APNS",
>       "CERTIFICATE": "/path/to/your/certificate.pem",
>      "TOPIC": "com.example.someappname.voip"
> },
> "my_ios_app-silent": {
>       "PLATFORM": "APNS",
>       "CERTIFICATE": "/path/to/your/certificate.pem",
>      "TOPIC": "com.example.someappname.shh"
> },
> "my_ios_app-dev": {
>       "PLATFORM": "APNS",
>       "CERTIFICATE": "/path/to/your/certificate.pem",
>       "APNS_USE_SANDBOX": True
> }
> ```

Hi
How Should I use these configs? I mean django-push-notifications config is defined as "PUSH_NOTIFICATIONS_SETTINGS" in settings.
How can I use two different "APNS_TOPIC"s?

**Comment by AzikDeveloper** [comment]
I am getting this error even tho i specified application_id when sending notification.
![Screenshot from 2023-10-05 14-51-14](https://github.com/jazzband/django-push-notifications/assets/78961300/040810f2-4a9b-4f25-b1a4-331985f997b7)
