### ISSUE TITLE
How to get registration_id of google chrome device? Any tutorial out there..

### ISSUE THREAD

**Issue by jaspindersingh83** [jleclanche/django-push-notifications#422]

**Comment by jaspindersingh83** [comment]
I am struck at providing registration_id of various users in Django admin panel

**Comment by jamaalscarlett** [comment]
When you say Google Chrome device, are you referring to a browser?  Or an Android device?

**Comment by jaspindersingh83** [comment]
Referring to a browser

**Comment by jamaalscarlett** [comment]
I'm not sure, but a device id is not needed to use this package.

**Comment by jaspindersingh83** [comment]
its mentioned in the README that registration_id is a required field

registration_id (required): The FCM/GCM registration id or the APNS token for the device.

**Comment by jamaalscarlett** [comment]
That depends on how you implement webpush.  That is handled client side, this is a server side package.
