### ISSUE TITLE
PIP package latest version

### ISSUE THREAD

**Issue by theromis** [jleclanche/django-push-notifications#435]
I need FCM notifications in my project, unfortunately 1.4.1 still doesn't have it.

I'm using fpm utility to build packages for my production.

`.gem/ruby/2.3.0/bin/fpm --python-pip /usr/bin/pip -fs python -t deb --no-python-downcase-name -p /tmp/out django-push-notifications`
this command runs `pip` with `--no-binary :all:` flag.
So I don't know why pip pulls out 1.4.1 version
```
# /usr/bin/pip download --no-clean --no-deps --no-binary :all: -i https://pypi.python.org/simple --build /tmp/package-python-build-7b309b186f34db30cf918a4697bf7cde1c58b1b833a84709691914ab122c/django-push-notifications django-push-notifications
Collecting django-push-notifications
  Using cached django-push-notifications-1.4.1.tar.gz
  Saved ./django-push-notifications-1.4.1.tar.gz
Successfully downloaded django-push-notifications
```

is it possible to make 1.5.0. make available to download this way, to build package using fpm (git repo doesn't work with `fpm` as well)?

**Comment by jleclanche** [comment]
Run `pip install --upgrade pip setuptools wheel` in a fresh virtualenv before installing this. I've made the conscious decision of not supporting ancient versions of those and that's probably what you're hitting.

**Comment by theromis** [comment]
@jleclanche thank you, this solution works
