### ISSUE TITLE
Support for GCM Unregister

### ISSUE THREAD

**Issue by gmorell** [jleclanche/django-push-notifications#44]
I'd like to see support for these messages being handled by the library: http://developer.android.com/google/gcm/adv.html#unreg 

Mostly the ability/option to automatically delete a GCM Client upon receipt of `NotRegistered` the message.

**Comment by jamaalscarlett** [comment]
https://github.com/jleclanche/django-push-notifications/pull/158

**Comment by jleclanche** [comment]
This should be fixed in 1.3.0. We handle NotRegistered now.
