### ISSUE TITLE
django-uuidfield 0.5.0 seems to support Python 3

### ISSUE THREAD

**Issue by guitarmanvt** [jleclanche/django-push-notifications#52]
Do you want to update the PyPI comment about uuidfield? https://pypi.python.org/pypi/django-push-notifications/1.0.1

Thanks. I'm trying out django-push-notifications now with Python 3.4.

**Comment by jleclanche** [comment]
Ok well upstream doesn't seem to care about this enough to make a release. If they do, please ping me and I'll bump the requirements.txt... in the mean time, Python 3 users can use Django 1.8 which has its own UUIDField (I just added compatibility for that)
